<br/>
Thank you for signing up for 2013 Jaguar Land Rover China Dealer Conference.<br/> 
<br/>
Please find below your account's details:<br/>
<br/>
Login: <?php echo $this->data['email'] ?><br/>
Password: <?php echo $this->data['password'] ?> <br/>
<br/>
If you have not completed all  the steps, please remind your information are required before 2013 March 31st.<br/>
<br/>
We are looking forward to seeing you at the Jaguar Land Rover China Dealer conference & Gala dinner.<br/>
<br/>
Click here to get more information regarding this event: http://www.2013-jlrc-conference.com <br/>
<br/>
If you have any questions, please do not hesitate to contact us via email or phone.<br/>
Email:  registration@2013-jlrc-conference.com <br/>
Tel: 021 6258 5325 (Working hours: 09:30 – 18:30).<br/>
<br/>
Best Regards,<br/>
<br/>
<br/>
Jaguar Land Rover