Hello <?php echo $this->data['first_name'] ?>, <br/>
<br/>
Thank you for signing up for 2013 Jaguar Land Rover China Dealer Conference. <br/>
<br/>
Your account's details: <br/>
<br/>
Login: <?php echo $this->data['email'] ?>,<br/>
Password: <?php echo $this->data['password'] ?> <br/>     
<br/>
We are looking forward to seeing you at the conference. <br/>
<br/>
If you have any questions, please don't hesitate contacting us.<br/>
<br/>
We are looking forward to seeing you at the conference <br/>
<br/>
Regards,<br/>
