<table>
                
                <tr><td>Last Name</td><td><?php echo $this->user['last_name']; ?></td></tr>
                <tr><td style="width:40%;">First Name</td><td><?php echo $this->user['first_name']; ?></td></tr>
                <tr><td style="width:40%;">Email</td><td><?php echo $this->user['email']; ?></td></tr>
                <tr><td>Gender</td><td><?php echo $this->user['gender']; ?></td></tr>
                <tr><td>ID/PASSPORT</td><td><?php echo $this->user['id_passport_number']; ?></td></tr>
                <tr><td>CITY</td><td><?php echo $this->user['city']; ?></td>
                <tr><td>Position</td><td><?php $this->user['position']; ?></td></tr>
                
                <?php if ($this->user['position'] == 'partner') { ?>
                
                <tr><td style="text-indent: 50px;">Company Name</td><td><?php echo $this->user['company_name']; ?></td></tr>
                <tr><td style="text-indent: 50px;">Title</td><td><?php echo $this->user['company_title']; ?></td></tr>
                    
                <?php } else if ($this->user['position'] == 'manager') { ?>

                <tr><td style="text-indent: 50px;">DMS Code</td><td><?php echo $this->user['dms']; ?></td></tr>

                <?php } else if ($this->user['position'] == 'group_head') { ?>
                    
                <tr><td style="text-indent: 50px;">Group Name</td><td><?php echo $this->user['group_head_name']; ?></td></tr>
                <tr><td style="text-indent: 50px;">Title</td><td><?php echo $this->user['group_title'];?></td></tr>
                    
                <?php } ?>
            </table>
            
            
                <table style="width: 60%; padding-top: 30px;" >
                    <tr><td>Arrival Date</td><td><?php echo $this->user['arrival_date']; ?></td></tr>
                    <tr><td style="width:40%;">Mean of Transportation</td><td><?php echo $this->user['arrival_transportation']; ?></td></tr>
                    <tr><td>From</td><td><?php echo $this->user['arrival_from_city'] ?></td></tr>
                    <tr><td>To</td><td>Shanghai</td></tr>
                    <tr><td>Estimated Arrival Time</td><td><?php echo $this->user['arrival_time']; ?></td></tr>
                </table>
                
                <table style="width: 60%;padding-top: 30px;">
                    <tr><td>Departure Date</td><td><?php echo $this->user['departure_date']; ?></td></tr>
                    <tr><td style="width:40%;">Mean of Transportation</td><td><?php echo $this->user['departure_transportation']; ?></td></tr>
                    <tr><td>From</td><td>Shanghai</td></tr>
                    <tr><td>To</td><td><?php echo $this->user['departure_to_city'] ?></td></tr>
                    <tr><td>Estimated Departure Time</td><td><?php echo $this->user['departure_time']; ?></td></tr>
                </table>
                
            
            
                <table style="width:70%; padding-top: 30px;" >
                    <tr>
                        <td>Will you stay at the Intercontinental Shanghai Expo Hotel?</td>
                        <td><?php if ($this->user['is_staying'] != '') { echo $this->user['is_staying'] ? 'Yes' : 'No'; } ?></td>
                    </tr>
                    
                    <?php if ($this->user['is_staying'] == '1') { ?>
                        <tr>
                            <td>Do you need our RSVP team to help you for booking your room?</td>
                            <td><?php if ($this->user['need_room_booking_help'] != '') { echo $this->user['need_room_booking_help'] ? 'Yes' : 'No'; } ?></td>
                        </tr>

                        <tr><td>Check-in Date</td><td><?php echo $this->user['check_in_date'] ?></td></tr>
                        
                        <tr><td>Check-out Date</td><td><?php echo $this->user['check_out_date'] ?></td></tr>
                        
                        <tr>
                            <td>Do you prefer non-smoking accomodation?</td>
                            <td><?php if ($this->user['non_smoking'] != '') { echo $this->user['non_smoking'] ? 'Yes' : 'No'; } ?></td>
                        </tr>
                        
                        <tr>
                            <td>Room Type</td>
                            <td><?php  if ($this->user['room_type'] != '') { echo $this->user['room_type']; } ?></td>
                        </tr>

                        <tr><td>Guest Name</td><td><?php echo $this->user['guest_name'] ?></td></tr>
                        
                    <?php } else if ($this->user['is_staying'] == '0') { ?>
                        <tr><td>Reasons Not to Stay</td><td><?php echo $this->user['not_staying_reason'] ?></td></tr>
                    <?php } ?>
                        
                    <tr>
                        <td>Will you join the complimentary lunch?</td>
                        <td><?php if ($this->user['is_joining_lunch'] != '') { echo $this->user['is_joining_lunch'] ?  'Yes' : 'No'; } ?></td>
                    </tr>
                
         
            </table>