<table id="new-user-admin-notice" width="80%">
    <tr>
        <th width="60%"></th>
        <th width="30%"></th>
    </tr>
    
    <tr>
        <td>First Name</td>
        <td><?php echo $this->data['first_name'] ?></td>
    </tr>

    <tr><td>Last Name</td><td><?php echo $this->data['last_name'] ?></td></tr>
    <tr><td>Email</td><td><?php echo $this->data['email'] ?></td></tr>
    
    <tr><td>Gender</td><td><?php echo $this->data['gender'] ?></td></tr>
    <tr><td>ID/Passport Number</td><td><?php echo $this->data['id_passport_number'] ?></td></tr>
    <tr><td>Tel</td><td><?php echo $this->data['tel'] ?></td></tr>
    <tr><td>Mobile</td><td><?php echo $this->data['mobile'] ?></td></tr>
    <tr><td>City</td><td><?php echo $this->data['city_id'] ?></td></tr>
    <tr><td>Position</td><td><?php echo $this->data['position'] ?></td></tr>
    
    <tr><td>&nbsp;</td><td></td></tr>
    <tr><td>Arrival Date</td><td><?php echo $this->data['arrival_date'] ?></td></tr>
    <tr><td>Mean of transportation</td><td><?php echo $this->data['arrival_transportation'] ?></td></tr>
    <tr><td>From</td><td><?php echo $this->data['arrival_from'] ?></td></tr>
    <tr><td>To</td><td>Shanghai</td></tr>
    <tr><td>Estimated Arrival Time</td><td><?php echo $this->data['arrival_time'] ?></td></tr>
    
    <tr><td>&nbsp;</td><td></td></tr>
    <tr><td>Departure Date</td><td><?php echo $this->data['departure_date'] ?></td></tr>
    <tr><td>Mean of transportation</td><td><?php echo $this->data['departure_transportation'] ?></td></tr>
    <tr><td>From</td><td>Shanghai</td></tr>
    <tr><td>To</td><td><?php echo $this->data['departure_to'] ?></td></tr>
    <tr><td>Estimated Departure Time</td><td><?php echo $this->data['departure_time'] ?></td></tr>
    
    <tr><td>&nbsp;</td><td></td></tr>
    <tr><td>Stay at the Intercontinental Shanghai Expo Hotel?</td><td><?php if (isset($this->data['is_staying'])) { echo $this->data['is_staying'] ? "Yes" : "No"; } ?></td></tr>
    <?php if ($this->data['is_staying']) { ?>
    
        <tr>
            <td>Room Type</td>
            <?php if ($this->data['room_type']) { ?>
            <td><?php echo $this->data['room_type'] ?></td>
            <?php } ?>
        </tr>
                    
        <tr>
            <td>Room Shared With</td>
            <td><?php echo $this->data['guest_name'] ?></td>
        </tr>
        
    <?php } else if ($this->data['is_staying'] == null){ ?>
        
        <tr>
            <td>Not Staying Reasons</td>
            <td><?php echo $this->data['not_staying_reason'] ?></td>
        </tr>
        
    <?php } ?>
    
    <tr>
        <td>Is joining Lunch</td>
        <td><td><?php if (isset($this->data['is_joining_lunch'])) { echo $this->data['is_staying'] ? "Yes" : "No"; } ?></td></td>
    </tr>
</table>