<div id="message">
    
    <div id="main-top-border"></div>
    
    <div id="main-content">
        <div id="main-content-title">NOT ATTENDING THE CONFERENCE</div>
        <div id="unattending">
            <form method="post" action="<?php echo $this->url(array('controller' => 'message', 'action' => 'unattending'), 'default'); ?>" id="message-form" enctype="application/x-www-form-urlencoded">
                <div class="left">
                    <div class="row"><label>FIRST NAME</label><div class="field"><?php echo $this->form->first_name ?></div></div>
                    <div class="row"><label>LAST NAME</label><div class="field"><?php echo $this->form->last_name ?></div></div>
                    <div class="row"><label>EMAIL</label><div class="field"><?php echo $this->form->email ?></div></div>
                    <div class="row"><label>DEALERSHIP NAME</label><div class="field"><?php echo $this->form->dealership_name ?></div></div>    
                    <div class="row"><label>DEALERSHIP ADDRESS</label><div class="field"><?php echo $this->form->dealership_addr ?></div></div>    
                    <div class="row"><label>DEALERSHIP REGION</label><div class="field"><?php echo $this->form->dealership_region ?></div></div>    
                </div>
                
                <div class="right">
                    <div class="row">
                        <label>MESSAGE</label>
                        <div class="row2"><?php echo $this->form->message ?></div>
                    </div>
                </div>

                <div class="bottom clearfix">
                    <input type="submit" id="btnSubmit" class="btn" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
<div id="form-errors"><ul><ul></div>

<script type="text/javascript">
$(document).ready(function(){
    
    
    $('#btnSubmit').click(function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/message/validate", 
            data: {
                'first_name': $('#first_name').val(), 
                'last_name': $('#last_name').val(), 
                'email': $('#email').val()
            },
            success: function(response) {
                if (response.success == true) {
                    $('#btnSubmit').unbind('click');
                    $('#message-form').submit();
                } else if (response.success == false) {
                    $('#form-errors ul').empty();
                    $('input').removeClass('error');
                    $('#form-errors ul').append('<li>' + 'Our records indicate that you have an account with that email address. ' + '</li>');
                    $('#email').addClass('error');
                    $('#form-errors').dialog('open');
                } else {
                    outputFormErrorMessages(response);
                }
            }
        });
    });

    $('#form-errors').dialog({
        autoOpen: false,
        modal: true,
        title: 'SIGN IN',
        width: 500,
        show: { effect: 'fade', duration: 500 },
        hide: { effect: 'hide', duration: 500 },
        buttons: {
            'Close': function(){
                $(this).dialog("close");
            }
        }
    });
});

function outputFormErrorMessages(response) 
{
    $('#form-errors ul').empty();
    $('input').removeClass('error');
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            $('#form-errors ul').append('<li>' + k + ': ' + v1 + '</li>');
            $('#' + k).addClass('error');
        });
    });
    $('#form-errors').dialog('open');
}
</script>