<div id="message">
    
    <div id="main-top-border"></div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('not_attending_the_conference') ?></div>
        <div id="unattending">
            <form method="post" action="<?php echo $this->url(array('controller' => 'message', 'action' => 'unattending'), 'default'); ?>" id="message-form" enctype="application/x-www-form-urlencoded">
                <div class="left" style="padding-top:25px !important;">
                    <div class="row"><label><?php echo $this->translate('first_name') ?></label><div class="field"><?php echo $this->form->first_name ?></div></div>
                    <div class="row"><label><?php echo $this->translate('last_name') ?></label><div class="field"><?php echo $this->form->last_name ?></div></div>
                    <div class="row"><label><?php echo $this->translate('email') ?></label><div class="field"><?php echo $this->form->email ?></div></div>
                </div>
                
                <div class="right" style="vertical-align:top !important;">
                    <div class="row"><label><?php echo $this->translate('please explain why') ?></label><div class="row2"><?php echo $this->form->message ?></div></div>
                </div>

                <div class="bottom clearfix" style="float:left;margin:20px !important;">
	                  <input type="submit" id="btnSubmit" class="btn" value="<?php echo $this->translate('submit') ?>">
                    <a href="/" class="btn" style="margin-top:2px;"><?php echo $this->translate('back') ?></a>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="form-errors"><ul><ul></div>

<script type="text/javascript">
$(document).ready(function(){
    
    
    $('#btnSubmit').click(function(e) {
        e.preventDefault();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/message/validate", 
            data: {
                'first_name': $('#first_name').val(), 
                'last_name': $('#last_name').val(), 
                'email': $('#email').val()
            },
            success: function(response) {
                if (response.success == true) {
                    $('#btnSubmit').unbind('click');
                    $('#message-form').submit();
                } else {
                    outputFormErrorMessages(response);
                }
            }
        });
    });

    $('#form-errors').dialog({
        autoOpen: false,
        modal: true,
        title: 'NOT ATTENDING THE CONFERENCE',
        width: 500,
        show: { effect: 'fade', duration: 500 },
        hide: { effect: 'hide', duration: 500 },
        buttons: {
            'Close': function(){
                $(this).dialog("close");
            }
        }
    });
});

function outputFormErrorMessages(response) 
{
    $('#form-errors ul').empty();
    $('input').removeClass('error');
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            $('#form-errors ul').append('<li>' + $('#'+k).parent().siblings("label").html() + ': ' + v1 + '</li>');
            $('#' + k).addClass('error');
        });
    });
    $('#form-errors').dialog('open');
}
</script>
