<table id="unattending-mail" width="60%">
    <tr><th width="30%"></th><th width="70%"></th></tr>
    <tr><td>First Name</td><td><?php echo $this->data['first_name'] ?></td></tr>
    <tr><td>Last Name</td><td><?php echo $this->data['last_name'] ?></td></tr>
    <tr><td>Email</td><td><?php echo $this->data['email'] ?></td></tr>
    <tr><td>Message</td><td><?php echo $this->data['message'] ?></td></tr>
</table>