<div class="users">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content" style="width: 90%; margin: 10px auto;">
        <div id="main-content-title"><?php echo $this->translate('users') ?><a href="<?php echo $this->url(array('controller'=>'users', 'action' => 'export')) ?> " id="export-csv" class="small-btn" style="float: right; padding: 3px 10px;"><?php echo $this->translate('export') ?></a></div>
        <div id="users-list">
            
            <table cellspacing="0">
                <tr>
                    <th><?php echo $this->translate('last_name') ?></th>
                    <th><?php echo $this->translate('first_name') ?></th>
                    <th><?php echo $this->translate('gender') ?></th>
                    <th><?php echo $this->translate('id_passport_number') ?></th>
                    <th><?php echo $this->translate('tel') ?></th>
                    <th><?php echo $this->translate('mobile') ?></th>
                    <th><?php echo $this->translate('email') ?></th>
                    <th><?php echo $this->translate('city') ?></th>
                    <th><?php echo $this->translate('position') ?></th>
                    <th><?php echo $this->translate('group_name') ?></th>
                    <th><?php echo $this->translate('title') ?></th>
                    <th>DMS</th>
                    <th><?php echo $this->translate('company_name') ?></th>
                    <th><?php echo $this->translate('company_title') ?></th>
                    <th><?php echo $this->translate('arrival_date') ?></th>
                    <th><?php echo $this->translate('transportation') ?></th>
                    <th><?php echo $this->translate('from') ?></th>
                    <th><?php echo $this->translate('estimated_arrival_time') ?></th>
                    <th><?php echo $this->translate('departure_date') ?></th>
                    <th><?php echo $this->translate('transportation') ?></th>
                    <th><?php echo $this->translate('to') ?></th>
                    <th><?php echo $this->translate('estimated_departure_time') ?></th>
                    
                    <th><?php echo $this->translate('stay_at_intercontinental') ?></th>
                    <th><?php echo $this->translate('check_in_date') ?></th>
                    <th><?php echo $this->translate('check_out_date') ?></th>
                    <th><?php echo $this->translate('room_type_2') ?></th>
                    <th><?php echo $this->translate('guest') ?></th>
                    
                    <th><?php echo $this->translate('rsvp_team_help') ?></th>
                    <th><?php echo $this->translate('non_smoking_room') ?></th>
                    
                    <th><?php echo $this->translate('not_staying_reasons') ?></th>
                    <th><?php echo $this->translate('lunch') ?></th>
                </tr>
                <?php foreach ($this->users as $user) { ?>
                <tr>
                    <td><?php echo $user['last_name'] ?></td>
                    <td><?php echo $user['first_name'] ?></td>
                    <td><?php echo $this->translate($user['gender']); ?></td>
                    <td><?php echo $user['id_passport_number'] ?></td>
                    <td><?php echo $user['tel'] ?></td>
                    <td><?php echo $user['mobile'] ?></td>
                    <td><?php echo $user['email'] ?></td>
                    <td><?php echo $this->translate(trim($user['city'])) ?></td>
                    <td><?php echo $this->translate($user['position']) ?></td>
                    <td><?php echo $user['group_head_name'] ?></td>
                    <td><?php echo $user['group_title'] ?></td>
                    <td><?php echo $user['dms'] ?></td>
                    <td><?php echo $user['company_name'] ?></td>
                    <td><?php echo $user['company_title'] ?></td>
                    <td><?php echo $user['arrival_date']; ?></td>
                    <td><?php echo $this->translate($user['arrival_transportation']) ?></td>
                    <td><?php echo $this->translate(trim($user['arrival_from_city'])) ?></td>
                    <td><?php echo $user['arrival_time'] ?></td>
                    <td><?php echo $user['departure_date'];  ?></td>
                    <td><?php echo $this->translate($user['departure_transportation']) ?></td>
                    <td><?php echo $this->translate(trim($user['departure_to_city'])); ?></td>
                    <td><?php echo $user['departure_time'] ?></td>
                    
                    <td><?php if ($user['is_staying'] != '') { echo $user['is_staying'] ? $this->translate('shi') : $this->translate('bu_shi'); } ?></td>
                    <td><?php echo $user['check_in_date'] ?></td>
                    <td><?php echo $user['check_out_date'] ?></td>
                    <td><?php echo $this->translate($user['room_type']) ?></td>
                    <td><?php echo $user['guest_name'] ?></td>
                    
                    <td><?php if ($user['need_room_booking_help'] != '') { echo $user['need_room_booking_help'] ? $this->translate('xu_yao') : $this->translate('bu_xu_yao'); } ?></td>
                    <td><?php if ($user['non_smoking'] != '') { echo $user['non_smoking'] ? $this->translate('xu_yao') : $this->translate('bu_xu_yao'); } ?></td>
                    <td><?php echo $user['not_staying_reason'] ?></td>
                    <td><?php if ($user['is_joining_lunch'] != '') { echo $user['is_joining_lunch'] ? $this->translate('yes') : $this->translate('no'); } ?></td>
                </tr>
                <?php } ?>
            </table>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

<style type="text/css">
    
    table {
        width: 90%;
        padding-right: 10px;
    }
    table tr {
        width: 100%;
    }
   
    table tr th, table tr td {
        border: 1px solid #ccc;
        padding: 10px;
        white-space: nowrap;
    }
    table tr th {
        white-space: normal;
    }
    
</style>