<div id="forgotpassword">
	<h2>SE CONNECTER</h2>
	<p class="head">De retour parmis nous ?</p>

	<div class="form">
		<form action="<?php echo $this->url(array('controller' => 'people', 'action' => 'forgotpassword'), 'default'); ?>" method="post" enctype="application/x-www-form-urlencoded" name="forgotpassword">

			<div class="section clearfix">
				<div class="column">
					<label> <span class="label"><span class="num">1</span> <?php echo $this->forgotPasswordForm->email_addr->getLabel(); ?></span>
						<span class="field"><?php echo $this->forgotPasswordForm->email_addr; ?></span>
					</label>
				</div>
			
				<div class="column">
					<label> <span class="label"><span class="num">2</span> Validez</span>
						<span class="field"><?php echo $this->forgotPasswordForm->forgotpassword_submit; ?></span>
					</label>
				</div>

			</div>
			
		</form>
	</div>
	
	<div class="message" style="display: none;">
		<p>Un e-mail a été envoyé à l'adresse indiquée avec vos nouveaux identifiants.</p>
	</div>
	
</div>

<script type="text/javascript">
$(function() {
	$('#forgotpassword form').ajaxForm({dataType: 'json', success : function(res) {
		if(res === true) {
			$('#forgotpassword form').hide();
			$('#forgotpassword .message').show();
		} else {
			$('#forgotpassword span.errors').remove();
			checkErrors(res);
		}
    }});

    function checkErrors(res) {
		$('input').removeClass('error');
		$.each(res, function(i, j) {
			var field = $('#' + i);
			field.addClass('error');
			if (typeof j == "object") {
				$.each(j, function(k, l) {
					field.after('<span class="errors">' + l + '</span>');
				});
			}
		});
    }
});
</script>