<div class="users">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li class="active"><a href="/users">My Profile</a></li>
                <li><a href="/event/venue">Venue Information</a></li>
                <li><a href="/event/conf-lib">Conference Library</a></li>
                <li><a href="/event/gallery">Gallery</a></li>
                <li><a href="/event/survey">Survey</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">Registration Information 
            <span style="float:right; ">
                <?php if (isset($this->isLogged)) { ?>
                    <a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>" style="text-decoration: none; font-style: italic; font-weight: normal;color: black;">Logout</a>
                <?php } ?>
            </span>
        </div>
        <div id="profile">
            <table>
                <tr><td>Last Name</td><td><?php echo $this->user->last_name ?></td></tr>
                <tr><td>First Name</td><td><?php echo $this->user->first_name ?></td></tr>
                <tr><td>Gender</td><td><?php echo $this->user->gender ?></td></tr>
                <tr><td>ID/Passport Number</td><td><?php echo $this->user->id_passport_number ?></td></tr>
                <tr><td>Email</td><td><?php echo $this->user->email ?></td></tr>
                <tr><td>Attending the event?</td><td><?php echo $this->user->is_attending ? 'Yes' : 'No'; ?></td></tr>
                <tr><td>Tel</td><td><?php echo $this->user->tel ?></td></tr>
                <tr><td>Mobile</td><td><?php echo $this->user->mobile ?></td></tr>
                <tr><td>Position</td><td><?php echo $this->user->position ?></td></tr>
                <?php if ($this->user->position == 'partner') { ?>
                    <tr><td>Company Name</td><td><?php echo $this->user->company_name ?></td></tr>
                    <tr><td>Company Title</td><td><?php echo $this->user->company_title ?></td></tr>
                <?php } else if ($this->user->position == 'general_manager') { ?>
                    <tr><td>DMS Code</td><td><?php echo $this->user->dms_code ?></td></tr>
                <?php } else { ?>
                    <tr><td>Group name</td><td><?php echo $this->user->group_name ?></td></tr>
                    <tr><td>Group Title</td><td><?php echo $this->user->group_title ?></td></tr>
                <?php } ?>
                <tr><td>City</td><td><?php echo $this->user->city_id ?></td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Arrival Date</td><td><?php echo $this->user->arrival_date ?></td></tr>
                <tr><td>Mean of Transportation</td><td><?php echo $this->user->arrival_transportation ?></td></tr>
                <tr><td>From</td><td><?php echo $this->user->arrival_from ?></td></tr>
                <tr><td>To</td><td>Shanghai</td></tr>
                <tr><td>Estimated Arrival Time</td><td><?php echo $this->arrival_time ?></td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Departure Date</td><td><?php echo $this->user->departure_date ?></td></tr>
                <tr><td>Mean of Transportation</td><td><?php echo $this->user->departure_transportation ?></td></tr>
                <tr><td>From</td><td>Shanghai</td></tr>
                <tr><td>To</td><td><?php echo $this->user->departure_to ?></td></tr>
                <tr><td>Estimated Departure Time</td><td><?php echo $this->departure_time ?></td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Intercontinental Shanghai Expo Hotel room type</td><td><?php echo $this->user->room_type ?></td></tr>
                <tr><td>Guest name to share room with</td><td><?php echo $this->user->guest_name ?></td></tr>
                <tr><td>Staying at Intecontinental Shanghai Expo Hotel</td><td><?php echo $this->user->not_staying ? 'No' : 'Yes'; ?></td></tr>
                <tr><td>Joining complimentary lunch at the Intercontinental Shanghai Expo Hotel between 11:30am - 12:20pm on April 8th</td><td><?php echo $this->user->is_joining_lunch ?></td></tr>
                
            </table>
        </div>
    </div>
</div>