<div class="users">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li class="active"><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers_and_venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('my_profile') ?><a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'edit', 'id' => $this->user->uid)) ?> " id="edit-profile" class="small-btn"><?php echo $this->translate('edit_profile') ?></a></div>
        <div id="profile">
            
            <table>
                <tr><td>Last Name</td><td><?php echo $this->user->last_name ?></td></tr>
                <tr><td>First Name</td><td><?php echo $this->user->first_name ?></td></tr>
                <tr><td>Gender</td><td><?php echo $this->user->gender ?></td></tr>
                <tr><td>ID/Passport Number</td><td><?php echo $this->user->id_passport_number ?></td></tr>
                <tr><td>Email</td><td><?php echo $this->user->email ?></td></tr>
                <tr><td>Attending the event?</td><td><?php echo $this->user->is_attending ? 'Yes' : 'No'; ?></td></tr>
                <tr><td>Tel</td><td><?php echo $this->user->tel ?></td></tr>
                <tr><td>Mobile</td><td><?php echo $this->user->mobile ?></td></tr>
                <tr><td>Position</td><td><?php echo $this->user->position ?></td></tr>
                <?php if ($this->user->position == 'partner') { ?>
                    <tr><td>Company Name</td><td><?php echo $this->user->company_name ?></td></tr>
                    <tr><td>Company Title</td><td><?php echo $this->user->company_title ?></td></tr>
                <?php } else if ($this->user->position == 'manager') { ?>
                    <tr><td>DMS Code</td><td><?php echo $this->user->dms_code ?></td></tr>
                <?php } else { ?>
                    <tr><td>Group name</td><td><?php echo $this->user->group_name ?></td></tr>
                    <tr><td>Group Title</td><td><?php echo $this->user->group_title ?></td></tr>
                <?php } ?>
                <tr><td>City</td><td><?php echo $this->user->city_en_name ?></td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Arrival Date</td><td><?php echo $this->user->arrival_date ?></td></tr>
                <tr><td>Mean of Transportation</td><td><?php echo $this->user->arrival_transportation ?></td></tr>
                <tr><td>From</td><td><?php echo $this->user->arrival_from_en_name ?></td></tr>
                <tr><td>To</td><td>Shanghai</td></tr>
                <tr><td>Estimated Arrival Time</td><td><?php echo $this->arrival_time ?></td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Departure Date</td><td><?php echo $this->user->departure_date ?></td></tr>
                <tr><td>Mean of Transportation</td><td><?php echo $this->user->departure_transportation ?></td></tr>
                <tr><td>From</td><td>Shanghai</td></tr>
                <tr><td>To</td><td><?php echo $this->user->departure_to_en_name ?></td></tr>
                <tr><td>Estimated Departure Time</td><td><?php echo $this->departure_time ?></td></tr>
                
                <tr><td>&nbsp;</td><td></td></tr>
                <tr><td>Stay at the Intercontinental Shanghai Expo Hotel</td><td><?php echo $this->user->is_staying ? "YES" : "NO"; ?></td></tr>
                <?php if ($this->user->is_staying) { ?> 
                    <tr><td>Room Type</td><td><?php echo $this->user->room_type ?></td></tr>
                    <tr><td>Room shared with</td><td><?php echo $this->user->guest_name ?></td></tr>
                <?php } else { ?>
                    <tr><td>Reason</td><td><?php echo $this->user->not_staying_reason ?></td></tr>
                <?php } ?>
                <tr><td>Joining complimentary lunch at the Intercontinental Shanghai Expo Hotel between 11:30am - 12:20pm on April 8th</td><td><?php echo $this->user->is_joining_lunch ? 'YES' : 'NO'; ?></td></tr>
            </table>
        </div>
    </div>
</div>