<div id="login">
	<h2>SE CONNECTER</h2>
	<p class="head">De retour parmis nous ?</p>

	<div class="form">
		<form
			action="<?php echo $this->url(array('controller' => 'people', 'action' => 'user'), 'default'); ?>" method="post" enctype="application/x-www-form-urlencoded" name="login">

			<div class="section clearfix">
				<div class="column">
					<label>
						<span class="label"><span class="num">1</span> <?php echo $this->loginForm->email_addr->getLabel(); ?></span>
						<span class="field"><?php echo $this->loginForm->email_addr; ?></span>
					</label>
				</div>
				<div class="column">
					<label>
						<span class="label"><span class="num">2</span> <?php echo $this->loginForm->password->getLabel(); ?></span>
						<span class="field"><?php echo $this->loginForm->password; ?></span>
					</label>
				</div>
				<div class="column">
					<label>
						<span class="label"><span class="num">3</span> Validez</span>
						<span class="field"><?php echo $this->loginForm->login_submit; ?></span>
					</label>
				</div>
				<div class="normal clearfix">
					<label>
						<span class="field"><?php echo $this->loginForm->remember; ?></span>
						<span class="label"><?php echo $this->loginForm->remember->getLabel(); ?></span>
					</label>
				</div>
				
				<div class="normal clearfix">
					<label>
						<span class="label">Vous avez perdu votre mot de passe ? <a class="fancybox-forgotpassword fancybox.ajax" href="<?php echo $this->url(array('controller' => 'people', 'action' => 'forgotpassword'), 'default'); ?>">Cliquez ici</a>.</span>
					</label>
				</div>
			</div>

			<div style="text-align: center;">
				<p class="text">
					Si vous n’avez pas encore de compte Citoyens de la Route, prenez 2 minutes pour inscrire, <a href="#" onclick="$('.fancybox.register').trigger('click');">cliquez ici</a>.
				</p>
				<p class="text">Encore plus simple, utilisez votre compte facebook pour pré-remplir votre profil.</p>
				<button type="button" class="facebook">SE CONNECTER AVEC FACEBOOK</button>
			</div>

			
			
		</form>
	</div>
</div>

<script type="text/javascript">
$(function() {
	$('#login form').ajaxForm({dataType: 'json', success : function(res) {
		if(res === true) {
			location.reload();
		} else {
			$('#login span.errors').remove();
			checkErrors(res);
		}
    }});
	
    function checkErrors(res) {
		$('input').removeClass('error');
		$.each(res, function(i, j) {
			var field = $('#' + i);
			field.addClass('error');
			if (typeof j == "object") {
				$.each(j, function(k, l) {
					field.after('<span class="errors">' + l + '</span>');
				});
			}
		});
    }

    var Login = {
	    status : '',
	    
	    initialize : function()
	    {
	        this.checkLogin();
	        this.submitForm();
	    },
	    
	    submitForm : function()
	    {
	        var self = this;
	        $('button.facebook').click(function() {
	            self.checkLogin()
	            
	            if (self.status != 'connected') {
	                FB.login(function(data) {
	                	self.me();
		            }, {scope: 'email,user_relationships'});
	
	              return false;
	            } else {
		            self.me();
	            }
	        });
	    },
	    
	    checkLogin : function()
	    {
	        var self = this;
	        FB.getLoginStatus(function(response) {
	            self.status = response.status;
	        });
	    },

	    me : function(data)
	    {
	    	FB.api('/me', function(res) {
		    	$.post('<?php echo $this->url(array('controller' => 'people', 'action' => 'facebook'), 'default'); ?>', res, function(data) {
			    	if(data === true) {
			    		location.reload();
			    	} else {
			    		$('.fancybox.register').trigger('click');
			    	}
				}, 'json');
			});
	    }
	    
	};

	Login.initialize();

	$('.fancybox-forgotpassword').fancybox();
    
});
</script>