 <div id="userSignUp">
    <form enctype="multipart/form-data" id="formSignUp" action="<?php echo $this->baseUrl(); ?>/people/register" method="<?php echo $this->form->getMethod() ?>">
        <div id="formSignUpStep1">
            <h3>Créer un compte</h3>
            <p class="subtitle italic georgia orange">C'est Simple, Rapide et Gratuit !</p>
            <p class="subtitle grey arial normal">Vous accèderez ainsi à tout l'univers de Citoyens de la Route</p>
            <div class="inner clearfix gradient">
                <div class="column georgia italic fs12">
                    <span class="violet fs24">1</span> Entrez votre adresse email
                    <?php echo $this->form->email_addr; ?>
                </div>

                <div class="column georgia italic fs12">
                    <span class="violet fs24">2</span> Choisissez un mot de passe
                    <?php echo $this->form->password; ?>
                </div>

                <div class="column georgia italic fs12">
                    <span class="violet fs24">3</span> Confirmez votre mot de passe
                    <?php echo $this->form->password2; ?>
                </div>

                <div class="column georgia italic fs12">
                    <span class="violet fs24">4</span> Validez votre inscription
                    <input type="submit" value="<?php echo $this->translate('Je crée mon compte') ?>" id="bContinue">
                </div>
            
            	<div id="agree_term" class="georgia fs12 italic">
                    <label><input type="checkbox" name="agree_term">
                    J'accepte les <a href="#" class="orange">conditions générales d'utilisations</a> du site citoyensdelaroute.fr</label>
            	</div>
            </div>
        </div>

        <div id="formSignUpStep2" style="display: none;">
            <h3>Créer un compte</h3>
            <p class="subtitle italic georgia orange bold">Mieux vous connaître</p>
        
            <div class="inner clearfix gradient">
                <div class="left">
                    <div><label><span class="georgia italic fs12">Situation familiale : </span><?php echo $this->form->relationship_status; ?></label></div>
                    <div><label><span class="georgia italic fs12">Nom* : </span><?php echo $this->form->last_name ?></label></div>
                    <div><label><span class="georgia italic fs12">Prénom* : </span><?php echo $this->form->first_name ?></label></div>
                    <div><label><span class="georgia italic fs12">Sexe* : </span><?php echo $this->form->sex ?></label></div>
        	</div>
        		
        	<div class="right">
                    <div><label><span class="georgia italic fs12">Vous êtes plutôt : </span><label class="georgia italic fs12"><?php echo $this->form->live; ?></label></label></div>
                    <div><label><span class="georgia italic fs12">Code postal : </span><input id="zip" type="text"></label></div>
                    <div><label><span class="georgia italic fs12">Niveau d'étude : </span><?php echo $this->form->degree; ?></label></div>
                    <div><label><span class="georgia italic fs12">CSP : </span><?php echo $this->form->csp; ?></label></div>
        	</div>
        		
	        <div class="continue">
                    <input type="submit" value="Passer à l'étape suivante" id="bContinue2">
	        </div>
            </div>
            
            <p class="fs11">les champs marqués d'une (*) sont obligatoires</p>
        </div>

        <div id="formSignUpStep3" style="display: none;">
            <h3>Créer un compte</h3>
                <p class="subtitle italic georgia orange bold">Quel automobiliste êtes-vous ?</p>
        	<div class="inner clearfix gradient">
                    <div class="left">
                        <div><span class="georgia italic fs12">Vous utilisez votre véhicule pour des raisons :</span> <label class="georgia italic fs12"><?php echo $this->form->reason_driver ?></label></div>
                        <div class="clearfix"><label><span class="georgia italic fs12">Combien de kilomètres annuels faites-vous ? </span><?php echo $this->form->driving_km_per_year ?></label></div>
                        <div class="clearfix"><label><span class="georgia italic fs12">Combien de kilomètres passez-vous dans les bouchons / j. ouvrés ?</span><?php echo $this->form->miles_caps; ?></label></div>
                        <div class="clearfix"><label><span class="georgia italic fs12">Utilisez-vous les transports en commun ? </span><?php echo $this->form->use_public_transportation ?></label></div>
                    </div>

                    <div class="right">
                        <div><label><span class="georgia italic fs12">Combien de véhicules avez-vous ? </span><?php echo $this->form->own_car_number ?></label></div>
                        <div><label><span class="georgia italic fs12">Possédez-vous un deux-roues ?</span><?php echo $this->form->ride_bike ?></label></div>
                    </div>
        	</div>
        
        	<p class="subtitle italic georgia orange bold">Véhicule Principal</p>
                <div class="inner clearfix gradient">
                    <div class="row">
                        <label><span class="georgia italic fs12">Marque de votre véhicule ?</span>
                            <select name="car_brand" id="car_brand">
                                <option value=""></option>
                            </select>
                        </label>
                    </div>

                    <div class="row">
                        <label><span class="georgia italic fs12">Modèle ?</span>
                            <select name="car_model" id="car_model">
                                <option value=""></option>
                            </select>
			</label>
                    </div>
                    
                    <div class="row"><label><span class="georgia italic fs12">Son age ?</span> <input type="text" name="car_age" id="car_age" value=""></label></div>
        	</div>
            
        	<p class="subtitle italic georgia orange bold">Quels sujets souhaiteriez vous voir traités par Citoyens de la Route ?</p>
                <div class="inner clearfix gradient georgia italic fs12">
                    <?php foreach ($this->qa as $row) { ?>
	            <div class="stack clearfix">
	                <div class="question"><?php echo $row[0]['question']; ?></div>
                        <?php // ?>
	                <?php if ($row[0]['type'] == 'cb') { ?>
	                    <?php foreach ($row as $answer ) { ?>
	                    <div class="answer"><input type="checkbox" name="answer_id_<?php echo $answer['answer_id']; ?>" name="answer_id_<?php echo $answer['answer_id']; ?>"> <?php echo $answer['answer']; ?></div>
	                    <?php } ?>
	                <?php } else { ?>
	                    <?php foreach ($row as $answer) { ?>
	                    <div class="answer"><input type="text" style="width: 850px; margin-top: 5px;" name="answer_id_<?php echo $answer['answer_id']; ?>" name="answer_id_<?php echo $answer['answer_id']; ?>"></div>
	                    <?php } ?>
	                <?php } ?>
	            </div>
	            <?php } ?>
            
	            <div id="notification">
	                <div><label><span class="georgia italic fs12"><input type="checkbox" name="optin_partners"> Recevoir des informations de la part de nos partenaires.</span></label></div>
	                <div><label><span class="georgia italic fs12"><input type="checkbox" name="optin_newsletter"> Recevoir la newsletter hebdomadaire.</span></label></div>
	                <div><label><span class="georgia italic fs12"><input type="checkbox" checked="checked" name="optin_subject"> Recevoir des notifications sur les sujets qui m’intéressent.</span></label></div>
	            </div>
            
	            <div class="continue">
	                <input type="submit" value="Valider mon inscription" id="bContinue3">
	            </div>
                </div>
        </div>
    </form>
</div>


<script type="text/javascript">
    
$(document).ready(function() {

    $('#formSignUpStep2', '#formSignUpStep3').hide();
    
    $('#bContinue').click(function (event){
        event.preventDefault();
        $('#formSignUpStep1 .errors').remove();
        
        /* validate the 1st step user input. if successful then proceed to the 2nd step otherwise show error MSGs. */
        $.ajax({
            dataType: 'json',
            type: 'POST',
            url: '<?php echo $this->url(array('action'=>'validate-form')); ?>',
            data: {
                'email_addr':   $('#email_addr').val(),
                'password':     $('#password').val(),
                'password2':    $('#password2').val()
            },
            success: function(response) {
                if (!$('input[name="agree_term"]:checked').val()) {
                    $('#agree_term').append('<ul class="errors"><li>Vous devez accepter les conditions générales d\'utilisation pour continuer</li></ul>');
                }
                if (response == true) {
                    /* check if the email addr exists in the db */
                    $.ajax({
                        dataType: 'json',
                        type: 'POST',
                        url: '<?php echo $this->url(array('action' => 'is-registered-email')) ?>',
                        data: {
                            'email_addr':   $('#email_addr').val()
                        },
                        success: function(response) {
                            if (response.success == 1) {
                               if ($('input[name="agree_term"]:checked').val()) {
                                   $('#formSignUpStep1').hide();
                                   $('#formSignUpStep2').show();
                               }
                            } else {
                              	$('#email_addr').after('<ul class="errors"><li>L\'adresse e-mail que vous avez entrée est déjà utilisée.</li></ul>');
                            }
                        }
                    });
                } else {
                    outputFormErrorMessages(response);
                }
            }
        });
    });
    
    $('#bContinue2').click(function (event) {
        event.preventDefault();
        $('#formSignUpStep2 .errors').remove();
        
        /* validate the 2nd step user input. if successful then proceed to the 3rd step otherwise show error MSGs. */
        $.ajax({
            dataType: 'json',
            type: 'post',
            'url': '<?php echo $this->url(array('action'=>'validate-form')); ?>',
            data: {
                'sex':          $('#sex').val(),
                'first_name':   $('#first_name').val(),
                'last_name':    $('#last_name').val(),
                'live' :	($('#live-city:checked, #live-country:checked').val()) ? $('#live-city:checked, #live-country:checked').val() : '',
                'zip':          $('#zip').val()
            },
            success: function(response) {
                if (response != true) {
                    outputFormErrorMessages(response);
                }
                if ($('#zip').nextAll('.errors').html() == null) {
                    $.ajax({
                        dataType: 'json',
                        type: 'post',
                        'url': '<?php echo $this->url(array('action'=>'validate-zipcode')) ?>',
                        data: {
                            'zip': $('#zip').val()
                        },
                        success: function(response1) {
                            if (response1.success == true && response == true) {
                                $('#formSignUpStep2').hide();
                                $('#formSignUpStep3').show();
                            } else if (response1.success == false) {
                               $('<ul class="errors"><li>' + 'invalid zip cdoe' + '</li></ul>').insertAfter('#zip');
                            }
                        }
                    });
                } 
            }
        });
    }); 
    
    $('#bContinue3').click(function (event) {
        event.preventDefault();
        $('#formSignUpStep3 .errors').remove();
        
        if ($('#car_age').val() && !isInteger($('#car_age').val())) {
            $('<ul class="errors"><li>' + '<?php echo $this->translate('not an integer') ?>' + '</li></ul>').insertAfter('#car_age');
        }
        
        /* validate the 3rd step user input. if successful then submit the form and register the user otherwise show error MSGs. */
        $.ajax({
            dataType: 'json',
            type: 'post',
            'url': '<?php echo $this->url(array('action'=>'validate-form')); ?>',
            data: {
                'reason_driver':                $('#reason_driver-pro:checked, #reason_driver-pleasure:checked').val() ? $('#reason_driver-pro:checked, #reason_driver-pleasure:checked').val() : '',
                'driving_km_per_year':          $('#driving_km_per_year').val(),
                'miles_caps':                   $('#miles_caps').val(),
                'use_public_transportation':    $('#use_public_transportation option:selected').val(),
                'own_car_number':               $('#own_car_number').val(),
                'ride_bike':                    $('#ride_bike option:selected').val()
            },
            success: function(response) {
                if (response != true) 
                    outputFormErrorMessages(response);

                if ($('#formSignUpStep3 .errors').length == 0) {
                    $('#bContinue3').attr('disabled', true);
                    
                    var ppl_ans_data = {};
                    $('input[name^=answer_id_]').each(function(k) {
                        if ($(this).attr('type') == 'checkbox' && $(this).attr('checked')) {
                            ppl_ans_data[$(this).attr('name')] = 1;
                        }  
                        if ($(this).attr('type') == 'text' && $(this).val()) {
                            ppl_ans_data[$(this).attr('name')] = $(this).val();
                        }
                    });
                    
                    /* all inputs are valid, register user */
                    $.ajax({
                        dataType: 'json',
                        type: 'post',
                        'url': '<?php echo $this->url(array('action'=>'register-user')); ?>',
                        data: {
                            'people_data' : {
                                'first_name':                   $('#first_name').val(),
                                'last_name':                    $('#last_name').val(),
                                'email_addr':                   $('#email_addr').val(),
                                'sex':                          $('#sex').val(),
                                'relationship_status':          $('#relationship_status').val(),
                                'live' :                        $('#live-city:checked, #live-country:checked').val(),
                                'miles_caps':                   $('#miles_caps').val(),
                                'zip':                          $('#zip').val(),
                                'csp':                          $('#csp').val(),
                                'degree':                       $('#degree').val(),
                                'password':                     $('#password').val(),
                                'reason_driver' :               $('#reason_driver-pro:checked, #reason_driver-pleasure:checked').val(),
                                'driving_km_per_year':          $('#driving_km_per_year').val(),
                                'use_public_transportation':    $('#use_public_transportation option:selected').val(),
                                'own_car_number':               $('#own_car_number').val(),
                                'ride_bike':                    $('#ride_bike option:selected').val(),
                                'car_brand':                    $('#car_brand').val(),
                                'car_model':                    $('#car_model').val(),
                                'car_age':                      $('#car_age').val(),
                                'optin_partners':               $('input[name="optin_partners"]:checked').val() ? 1 : 0,
                                'optin_newsletter':             $('input[name="optin_newsletter"]:checked').val() ? 1 : 0,
                                'optin_subject':                $('input[name="optin_subject"]:checked').val() ? 1 : 0
                            }, 
                            'people_answer_data':               ppl_ans_data
                        },
                        success: function(response) {
                            $.fancybox.close();
                            window.location.reload();
                        }
                    });
                }
            }
        });
    });
    
    // request car brands
    $.ajax({
        dataType: 'json',
        type: 'POST',
        url: '<?php echo $this->url(array('controller'=>'people', 'action'=>'get-car-brands')); ?>',
        data: {
            'search': ''
        },
        success: function(response) {
            $.each(response, function (k, v) {
                $('#car_brand').append('<option value="'+ v +'">'+ v +'</option>');
            });
        }
    });
    
    // request car models
    $('#car_brand').change(function() {
        $('#car_model option:not(:first)').remove();
        $.ajax({
            dataType: 'json',
            type: 'POST',
            url: '<?php echo $this->url(array('controller'=>'people', 'action'=>'get-car-models')); ?>',
            data: {
                brand: $(this).val()
            },
            success: function(response) {
                $.each(response, function (k, v) {
                    $('#car_model').append('<option value="'+ k +'">'+ v +'</option>');
                });
            }
        });
    });
});

function autoSearchCities(obj){
    value = $(obj).val();
    if(value.length>0){
        $.ajax({
            dataType: 'json',
            type: 'POST',
            url: '<?php echo $this->url(array('action'=>'get-cities')); ?>',
            data: {
                'search': value
            },
            success: function(response) {
                $('#city_name' ).autocomplete({
                    source: response
                }); 
            }
        });
    }
}

function isInteger(val) {
    if(val==null) {
        return false;
    }
    
    if (val.length==0) {
        return false;
    }

    for (var i = 0; i < val.length; i++) {
        var ch = val.charAt(i)
        if (i == 0 && ch == "-")
            continue
        if (ch < "0" || ch > "9") {
            return false;
        }
    }
    return true;
}

function outputFormErrorMessages(response) {
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            if (k == 'live') {
                $('#' + 'live-country').parent().append('<ul class="errors"><li>' + v1 + '</li></ul>');
            } else if (k == 'reason_driver') {
                $('#' + 'reason_driver-pleasure').parent().append('<ul class="errors"><li>' + v1 + '</li></ul>');
            } else {
                $('<ul class="errors"><li>' + v1 + '</li></ul>').insertAfter('#' + k);
            }
        });
    });
}
</script>
