<div id="register">    
    
    <div id="breadcrumb">
        <div id="breadcrumb-wrapper">
            <ul>
                <li id="about" class="active"><?php echo $this->translate('menu_bar_guest_information') ?></li>
                <li id="trans"><?php echo $this->translate('menu_bar_transportation') ?></li>
                <li id="accomodation"><?php echo $this->translate('menu_bar_accomodation') ?></li>
            </ul>
        </div>
    </div>
    
    <div id="register-form">
        <div id="register-form-title"><?php echo $this->translate('register') ?></div>
        <div id="register-form-content">
            <form action="<?php echo $this->url(array('controller' => 'users', 'action' => 'register'), 'default'); ?>" method="post" enctype="application/x-www-form-urlencoded" >
            <div id="step-one" style="display: none;">
                <p class="general-notice"><?php echo $this->translate('step_1') . ': ' . $this->translate('menu_bar_guest_information') ?></p>
                <p class="important-notice"><?php echo $this->translate('important_notice_step_one') ?></p>
                <p class="general-notice"><?php echo $this->translate('general_notice_step_one') ?></p>

                <div class="left">
                    <div class="row clearfix"><label><?php echo $this->translate('first_name') ?></label><div class="field"><?php echo $this->stepOneForm->first_name; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('last_name') ?></label><div class="field"><?php echo $this->stepOneForm->last_name; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('gender') ?></label><div class="field"><div id="gender"><?php echo $this->stepOneForm->gender ?></div></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('id_passport_number') ?></label><div class="field"><?php echo $this->stepOneForm->id_passport_number ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('tel') ?></label><div class="field"><?php echo $this->stepOneForm->tel; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('mobile') ?></label><div class="field"><?php echo $this->stepOneForm->mobile; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('email') ?></label><div class="field"><?php echo $this->stepOneForm->email; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('confirm_email') ?></label><div class="field"><?php echo $this->stepOneForm->confirm_email; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('password') ?></label><div class="field"><?php echo $this->stepOneForm->password; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('confirm_password') ?></label><div class="field"><?php echo $this->stepOneForm->confirm_password; ?></div></div>
                    <div class="row clearfix"><label><?php echo $this->translate('city') ?></label><div class="field"><?php echo $this->stepOneForm->city_id; ?></div></div>
                </div>
                
                <?php if ($this->isGroupOne == true) { ?>
                <div class="right">
                    <div class="row clearfix">
                        <label><?php echo $this->translate('position') ?></label>
                        <div class="field">
                            <div id='position'><?php echo $this->stepOneForm->position; ?></div>
                            <div class="row" style="display: none;"><label><?php echo $this->translate('group_name') ?></label><div class="field"><?php echo $this->stepOneForm->group_name ?></div></div>
                            <div class="row" style="display: none;"><label><?php echo $this->translate('title') ?></label><div class="field"><?php echo $this->stepOneForm->group_title ?></div></div>
                            <div class="row" style="display: none;"><label><?php echo $this->translate('dms_code') ?></label><div class="field"><?php echo $this->stepOneForm->dms_code ?></div></div>
                            <div class="row" style="display: none;"><label><?php echo $this->translate('company_name') ?></label><div class="field"><?php echo $this->stepOneForm->company_name ?></div></div>
                            <div class="row" style="display: none;"><label><?php echo $this->translate('company_title') ?></label><div class="field"><?php echo $this->stepOneForm->company_title ?></div></div>
                        </div>
                    </div>
                </div>
                <?php } ?>
                <div class="section clearfix" style="margin-top: 30px; display: block; float: left;">
                    <a href="#" id="stepOneNextBtn" class="btn"><?php echo $this->translate('next') ?></a>
                    <a href="/" class="btn"><?php echo $this->translate('back') ?></a>
                </div>
            </div>
            
            <div id="step-two" style="display:none;">
                <p class="general-notice"><?php echo $this->translate('step_2') . ': ' . $this->translate('menu_bar_transportation') ?></p>
                <p class="important-notice"><?php echo $this->translate('important_notice_step_two') ?></p>
                <div class="form">
                    <div class="section clearfix">
                        <div class="left">
                            <div class="row clearfix"><label><?php echo $this->translate('arrival_date') ?></label><div class="field"><?php echo $this->stepTwoForm->arrival_date; ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('mean_of_transportation') ?></label><div class="field"><?php echo $this->stepTwoForm->arrival_transportation; ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('from') ?></label><div class="field"><?php echo $this->stepTwoForm->arrival_from ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('to') ?></label><div class="field"><span class="text"><?php echo $this->translate('shanghai') ?></span></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('estimated_arrival_time') ?></label><div class="field"><?php echo $this->stepTwoForm->arrival_time; ?></div></div>
                        </div>

                        <div class="right">
                            <div class="row clearfix"><label><?php echo $this->translate('departure_date') ?></label><div class="field"><?php echo $this->stepTwoForm->departure_date; ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('mean_of_transportation') ?></label><div class="field"><?php echo $this->stepTwoForm->departure_transportation; ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('from') ?></label><div class="field"><span class="text"><?php echo $this->translate('shanghai') ?></span></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('to') ?></label><div class="field"><?php echo $this->stepTwoForm->departure_to ?></div></div>
                            <div class="row clearfix"><label><?php echo $this->translate('estimated_departure_time') ?></label><div class="field"><?php echo $this->stepTwoForm->departure_time; ?></div></div>
                        </div>
                    </div>
                    <div class="section clearfix" style="margin-top: 30px; display: block; float: left;">
                        <a href="#" id="stepTwoNextBtn" class="btn"><?php echo $this->translate('next') ?></a>
                        <a href="#" id="stepTwoSkipBtn" class="btn"><?php echo $this->translate('skip') ?></a>
                        <a href="#" id="stepTwoBackBtn" class="btn"><?php echo $this->translate('back') ?></a>
                    </div>
                </div>
            </div>
            
            <div id="step-three" style="display:none;">
                <p class="general-notice"><?php echo $this->translate('step_3') . ': ' . $this->translate('menu_bar_accomodation') ?></p>
                <p class="important-notice"><?php echo $this->translate('important_notice_step_three') ?></p>
                <div class="form">
                        <div class="left">
                            <div class="row"><label><?php echo $this->translate('is_staying') ?></label><div class="field"><?php echo $this->stepThreeForm->is_staying ?></div></div>
                            <div class="row"><label><?php echo $this->translate('is_joining_lunch') ?></label><div class="field"><?php echo $this->stepThreeForm->is_joining_lunch; ?></div></div>
                        </div>
                    <div class="right staying_at_hotel" style="display:none;">
                        <div class="row"><label><?php echo $this->translate('room_type') ?></label><div class="field"><?php echo $this->stepThreeForm->room_type; ?></div></div>
                        <div class="row"><label><?php echo $this->translate('guest_name') ?></label><div class="field"><?php echo $this->stepThreeForm->guest_name; ?></div></div>
                    </div>
                    <div class="right not_staying_at_hotel" style="display:none;">
                        <div class="row"><label class="small"><?php echo $this->translate('not_staying_reason') ?></label><div class="field"><?php echo $this->stepThreeForm->not_staying_reason ?></div></div>
                    </div>
                    <div class="section clearfix clear" >
                        <a href="#" id="stepThreeSubmitBtn" class="btn"><?php echo $this->translate('register') ?></a>
                        <a href="#" id="stepThreeBackBtn" class="btn"><?php echo $this->translate('back') ?></a>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
    
    
        
</div>
<div id="skip-step"></div>
<div id="popup-form"><ul></ul></div>
<div id="popup-reminder"></div>
<div id="popup-important-notice"></div>
<script type="text/javascript">
$(function() {
    
    $('#stepOneNextBtn').click(function() {
        var gender = $('input[name="gender"]:checked').val();
        var position = $('input[name="position"]:checked').val();
        $('#step-one .errors').remove();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/users/validate-step-one", 
            data: {
                'first_name':   $('#first_name').val(),
                'last_name':    $('#last_name').val(),
                'gender': (typeof(gender) == 'undefined') ? '' : gender,
                'id_passport_number': $('#id_passport_number').val(),
                'tel':   $('#tel').val(),
                'mobile':    $('#mobile').val(),
                'email':    $('#email').val(),
                'confirm_email': $('#confirm_email').val(),
                'password': $('#password').val(),
                'confirm_password': $('#confirm_password').val(),
                'position': (typeof(position) == 'undefined') ? '' : position,
            },
            success: function(response) {
                if (response.success == true) {
                    $('#step-one').hide();
                    $('ul li#about').removeClass('active');
                    $('ul li#trans').addClass('active');
                    $('#step-two').show();
                } else {
                    outputFormErrorMessages(response);
                }
            }
        });
        return false;
    });
    
    

    $('#stepTwoSkipBtn').click(function(e) {
        e.preventDefault();
        $('#skip-step').html('<?php echo $this->translate('skip_this_step') ?>');
        $('#skip-step').dialog('open');
    });
    
    $('#stepThreeSubmitBtn').click(function() {
    
        if ($('#popup-reminder').html() === '') {
            initPopupReminder('<?php echo $this->translate('popup_reminder') ?>');
        } else {
            $('#popup-reminder').dialog('open');
        }
    });
    
    $('#skip-step').dialog({
                autoOpen: false,
                modal: true,
                title: '<?php echo $this->translate('register') ?>',
                width: 500,
                show: { effect: 'fade', duration: 500 },
                hide: { effect: 'hide', duration: 500 },
                buttons: {
                    '<?php echo $this->translate('yes') ?>': function() {
                        //$(this).dialog("close");
                        //$('#step-two').hide();
                        //$('ul li#trans').removeClass('active');
                        //$('ul li#accomodation').addClass('active');
                        //$('#step-three').show();
                        if ($('#popup-reminder').html() === '') {
                            initPopupReminder('<?php echo $this->translate('popup_reminder') ?>');
                        } else {
                            $('#popup-reminder').dialog('open');
                        }
                    },
                    '<?php echo $this->translate('no') ?>': function(){
                        $(this).dialog("close");
                    }
                }
    });
    
    $('#popup-form').dialog({
                autoOpen: false,
                modal: true,
                title: '<?php echo $this->translate('register') ?>',
                width: 500,
                show: { effect: 'fade', duration: 500 },
                hide: { effect: 'hide', duration: 500 },
                buttons: {
                    'Close': function(){
                        $(this).dialog("close");
                    }
                }
    });
    
    $('#arrival_date').datepicker({ dateFormat: 'yy-mm-dd', minDate: new Date(2013, 4 - 1, 1), maxDate: new Date(2013, 4 - 1, 8)});
    $('#departure_date').datepicker({ dateFormat: 'yy-mm-dd', minDate: new Date(2013, 4 - 1, 9)});
    
    $('#arrival_time, #departure_time').timepicker({'timeFormat': 'H:i' });

});

function outputFormErrorMessages(response) {
    $('#popup-form ul').empty();
    $(".error").removeClass("error");
       
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            $('#popup-form ul').append('<li>' + $('#'+k).parent().siblings("label").html() + ': ' + v1 + '</li>');
            $('#' + k).addClass('error');
        });
    });
    
    $('#popup-form').dialog('open');
}

</script>