<div id="register">    
    
    <div id="breadcrumb">
        <div id="breadcrumb-wrapper">
            <ul>
                <li id="about" class="active">1. GUEST INFORMATION (Mandatory)</li>
                <li id="trans">2. TRANSPORTATION</li>
                <li id="accomodation">3. ACCOMODATION</li>
            </ul>
        </div>
    </div>
    
    <div id="register-form">
        <div id="register-form-title">REGISTER</div>
        <div id="register-form-content">
            <form action="<?php echo $this->url(array('controller' => 'users', 'action' => 'register'), 'default'); ?>" method="post" enctype="application/x-www-form-urlencoded" >
            <div id="step-one" style="display: none;">
                <p class="important-notice">YOUR PERSONAL INFORMATION WILL NOT BE DISPLAYED FOR ANY COMMERCIAL OR PUBLIC USE.</p>
                <p class="gengeral-notice">NOTE: IF YOU WANT TO INVITE ADDITIONAL GUEST, PLEASE CONTACT DIRECTLY WITH YOUR AREA BUSINESS MANAGER .</p>
                

                <div class="left">
                    <div class="row clearfix"><label>FIRST NAME</label><div class="field"><?php echo $this->stepOneForm->first_name; ?></div></div>
                    <div class="row clearfix"><label>LAST NAME</label><div class="field"><?php echo $this->stepOneForm->last_name; ?></div></div>
                    <div class="row clearfix"><label>GENDER</label><div class="field"><div id="gender"><?php echo $this->stepOneForm->gender ?></div></div></div>
                    <div class="row clearfix"><label>ID/PASSPORT NUMBER</label><div class="field"><?php echo $this->stepOneForm->id_passport_number ?></div></div>
                    <div class="row clearfix"><label>TELEPHONE NUMBER</label><div class="field"><?php echo $this->stepOneForm->tel; ?></div></div>
                    <div class="row clearfix"><label>MOBILE NUMBER</label><div class="field"><?php echo $this->stepOneForm->mobile; ?></div></div>
                    <div class="row clearfix"><label>EMAIL</label><div class="field"><?php echo $this->stepOneForm->email; ?></div></div>
                    <div class="row clearfix"><label>EMAIL CONFIRMATION</label><div class="field"><?php echo $this->stepOneForm->confirm_email; ?></div></div>
                    <div class="row clearfix"><label>PASSWORD</label><div class="field"><?php echo $this->stepOneForm->password; ?></div></div>
                    <div class="row clearfix"><label>PASSWORD CONFIRMATION</label><div class="field"><?php echo $this->stepOneForm->confirm_password; ?></div></div>
                    <div class="row clearfix"><label>CITY</label><div class="field"><?php echo $this->stepOneForm->city_id; ?></div></div>
                </div>
                
                <div class="right">
                    <div class="row clearfix">
                        <label>POSITION</label>
                        <div class="field">
                            <div id='position'><?php echo $this->stepOneForm->position; ?></div>
                            <div class="row" style="display: none;"><label>GROUP NAME</label><div class="field"><?php echo $this->stepOneForm->group_name ?></div></div>
                            <div class="row" style="display: none;"><label>TITLE</label><div class="field"><?php echo $this->stepOneForm->group_title ?></div></div>
                            <div class="row" style="display: none;"><label>DMS CODE</label><div class="field"><?php echo $this->stepOneForm->dms_code ?></div></div>
                            <div class="row" style="display: none;"><label>COMPANY NAME</label><div class="field"><?php echo $this->stepOneForm->company_name ?></div></div>
                            <div class="row" style="display: none;"><label>COMPANY TITLE</label><div class="field"><?php echo $this->stepOneForm->company_title ?></div></div>
                        </div>
                    </div>
                </div>
                <div class="section clearfix">
                    <div id="stepOneSubmitBtn"><?php echo $this->stepOneForm->step_one_next; ?></div>
                </div>
            </div>
            
            <div id="step-two" style="display:none;">
                <p class="important-notice">IMPORTANT NOTICE: GUESTS ARE IN CHARGE OF THEIR OWN TRANSFERS</p>
                <div class="form">
                    <div class="section clearfix">
                        <div class="left">
                            <div class="row clearfix"><label>ARRIVAL DATE</label><div class="field"><?php echo $this->stepTwoForm->arrival_date; ?></div></div>
                            <div class="row clearfix"><label>MEAN OF TRANSPORTATION</label><div class="field"><?php echo $this->stepTwoForm->arrival_transportation; ?></div></div>
                            <div class="row clearfix"><label>FROM</label><div class="field"><?php echo $this->stepTwoForm->arrival_from ?></div></div>
                            <div class="row clearfix"><label>TO</label><div class="field"><span class="text">Shanghai</span></div></div>
                            <div class="row clearfix"><label>ESTIMATED ARRIVAL TIME</label><div class="field"><?php echo $this->stepTwoForm->arrival_time; ?></div></div>
                        </div>

                        <div class="right">
                            <div class="row clearfix">
                                    <label>DEPARTURE DATE</label>
                                    <div class="field"><?php echo $this->stepTwoForm->departure_date; ?></div>
                            </div>

                            <div class="row clearfix">
                                    <label>MEAN OF TRANSPORTATION</label>
                                    <div class="field"><?php echo $this->stepTwoForm->departure_transportation; ?></div>
                            </div>
                            
                            <div class="row clearfix">
                                <label>FROM</label>
                                <div class="field"><span class="text">Shanghai</span></div>
                            </div>
                            
                            <div class="row clearfix">
                                <label>TO</label>
                                <div class="field"><?php echo $this->stepTwoForm->departure_to ?></div>
                            </div>
                            
                            <div class="row clearfix">
                                 <label>ESTIMATED DEPARTURE TIME</label>
                                 <div class="field"><?php echo $this->stepTwoForm->departure_time; ?></div>
                            </div>
                        </div>

                    </div>
                    <div class="section clearfix">
                        <div id="stepTwoNextBtn"><button class="btn">NEXT</button></div>
                        <div id="stepTwoSkipBtn"><button class="btn">SKIP</button></div>
                    </div>
                </div>
            </div>
            
            <div id="step-three" style="display:none;">
                <p class="important-notice">
                    IMPORTANT NOTICE: ALL ATTENDEES MUST STAY AT THE INTERCONTINENTAL SHANGHAI EXPO HOTEL ON APRIL 8TH (IF HOTEL ACCOMMODATION IS REQUIRED).<br>
                    A LIMITED NUMBER OF ROOMS ARE GUARANTEED AT A SPECIAL RATE OF 1,100 RMB NET PER NIGHT (BREAKFAST INCLUDED).
                    ACCOMMODATION AND TRANSFERS TO AND FROM THE HOTEL MUST BE ARRANGED BY ATTENDEES AT THEIR OWN EXPENSE.
                    IF YOU NEED ANY OTHER INFORMATION, PLEASE CONTACT OUR TEAM: + 86 (21) 62585325 OR + 86 (21) 62585320
                </p>
                <div class="form">
                        <div class="left">
                            <div class="row"><label>Will you stay at the Intercontinental Shanghai Expo Hotel?</label><div class="field"><?php echo $this->stepThreeForm->is_staying ?></div></div>
                            <div class="row">
                                 <label>Complimentary lunch is offered at the Intercontinental Shanghai Expo Hotel between 11:30am - 12:20pm on April 8th, will you join?</label>
                                 <div class="field"><?php echo $this->stepThreeForm->is_joining_lunch; ?></div>
                            </div>
                        </div>
                    <div class="right staying_at_hotel" style="display:none;">
                        <div class="row"><label>Intercontinental Shanghai Expo Hotel room type</label><div class="field"><?php echo $this->stepThreeForm->room_type; ?></div></div>
                        <div class="row"><label>If twin room shared with another guest, please precise guest name</label><div class="field"><?php echo $this->stepThreeForm->guest_name; ?></div></div>
                    </div>
                    <div class="right not_staying_at_hotel" style="display:none;">
                        <div class="row"><label class="small">Please explain why.</label><div class="field"><?php echo $this->stepThreeForm->not_staying_reason ?></div></div>
                    </div>
                    <div class="section clearfix">
                        <div id="stepThreeSubmitBtn"><input type="submit" value="Register" class="btn"/></div>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
    
    
        
</div>
<div id="reg-form-errors"><ul><ul></div>
<div id="skip-step"></div>
<script type="text/javascript">
$(function() {
    $("#reg-form-errors").hide().fadeIn(4000);
    $('#step-one').show();
    $('#step-two', '#step-three').hide();
    
    $('input[name="position"]').click(function(){
        showPosition();
    });
    
    $('#stepOneSubmitBtn').click(function(e) {
        e.preventDefault();
        var gender = $('input[name="gender"]:checked').val();
        var position = $('input[name="position"]:checked').val();
        $('#step-one .errors').remove();
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/users/validate-step-one", 
            data: {
                'first_name':   $('#first_name').val(),
                'last_name':    $('#last_name').val(),
                'gender': (typeof(gender) == 'undefined') ? '' : gender,
                'id_passport_number': $('#id_passport_number').val(),
                'tel':   $('#tel').val(),
                'mobile':    $('#mobile').val(),
                'email':    $('#email').val(),
                'confirm_email': $('#confirm_email').val(),
                'password': $('#password').val(),
                'confirm_password': $('#confirm_password').val(),
                'position': (typeof(position) == 'undefined') ? '' : position,
            },
            success: function(response) {
                if (response.success == true) {
                    $('#step-one').hide();
                    $('ul li#about').removeClass('active');
                    $('ul li#trans').addClass('active');
                    $('#step-two').show();
                } else {
                    outputFormErrorMessages(response);
                }
            }
        });
    });
    
    $('#stepTwoSkipBtn').click(function(e) {
        e.preventDefault();
        $('#skip-step').html('Are you Sure You Want to Skip This Step?');
        $('#skip-step').dialog('open');
    });
    $('#stepTwoNextBtn').click(function(e) {
        e.preventDefault();
        $('#step-two').hide();
        $('ul li#trans').removeClass('active');
        $('ul li#accomodation').addClass('active');
        $('#step-three').show();
    });

    $('#skip-step').dialog({
                autoOpen: false,
                modal: true,
                title: 'REGISTER',
                width: 500,
                show: { effect: 'fade', duration: 500 },
                hide: { effect: 'hide', duration: 500 },
                buttons: {
                    'YES': function() {
                        $(this).dialog("close");
                        $('#step-two').hide();
                        $('ul li#trans').removeClass('active');
                        $('ul li#accomodation').addClass('active');
                        $('#step-three').show();
                    },
                    'NO': function(){
                        $(this).dialog("close");
                    }
                }
    });
    
    $('#reg-form-errors').dialog({
                autoOpen: false,
                modal: true,
                title: 'REGISTER',
                width: 500,
                show: { effect: 'fade', duration: 500 },
                hide: { effect: 'hide', duration: 500 },
                buttons: {
                    'Close': function(){
                        $(this).dialog("close");
                    }
                }
    });
    
    $('#arrival_date, #departure_date').datepicker({ dateFormat: 'yy-mm-dd', minDate: new Date(2013, 4 - 1, 1), maxDate: new Date(2013, 4 - 1, 8)});
    
    $('#arrival_time, #departure_time').timepicker({'timeFormat': 'H:i' });

    $('#is_staying-1').click(function(e) {
        $('.staying_at_hotel').show();
        $('.not_staying_at_hotel').hide();
    }); 

    $('#is_staying-0').click(function(e) {
        $('.staying_at_hotel').hide();
        $('.not_staying_at_hotel').show();
    });
});

function outputFormErrorMessages(response) {
    $('#reg-form-errors ul').empty();
    $(".error").removeClass("error");
       
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            $('#reg-form-errors ul').append('<li>' + $('#'+k).parent().siblings("label").html() + ': ' + v1 + '</li>');
            $('#' + k).addClass('error');
        });
    });
    
    $('#reg-form-errors').dialog('open');
}

function showPosition()
{
    var value = $('input[name="position"]:checked').val();
    if (value === 'group_head') {
        $('#group_name').parent().parent().show();
        $('#group_title').parent().parent().show();
        $('#dms_code').parent().parent().hide();
        $('#company_name').parent().parent().hide();
        $('#company_title').parent().parent().hide();
    } else if (value === 'manager') {
        $('#group_name').parent().parent().hide();
        $('#group_title').parent().parent().hide();
        $('#dms_code').parent().parent().show();
        $('#company_name').parent().parent().hide();
        $('#company_title').parent().parent().hide();
    } else if (value === 'partner') {
        $('#group_name').parent().parent().hide();
        $('#group_title').parent().parent().hide();
        $('#dms_code').parent().parent().hide();
        $('#company_name').parent().parent().show();
        $('#company_title').parent().parent().show();
    }
}
</script>