<div id="main-top-border"></div>
<div id="main-wrapper-wrapper">
    <div id="index">
        <div id="main-content-login">
            <div id="login-text"></div>

            <div id="resetpassword">
                
                <div id="resetpassword-wrapper" >
                    
                    <div class="form">
                        <div class="bigger"><?php echo $this->translate('reset_password') ?></div>

                        <form id="reset-password-form" action="/users/process-reset-password" method="post" enctype="application/x-www-form-urlencoded" name="resetpassword">
                            
                            <?php echo $this->resetPasswordForm->uid ?>
                            <div class="row"><label><?php echo $this->translate('new_password') ?></label><div class="field"><?php echo $this->resetPasswordForm->password ?></div></div>
                            <div class="row"><label><?php echo $this->translate('confirm_new_password') ?></label><div class="field"><?php echo $this->resetPasswordForm->confirm_password ?></div>
                            <div class="row submit">
                                <div class="ajax-loader" style="margin-left: 250px; display: none;"></div>
                                <a href="#" id="btnResetPassword" class="btn"><?php echo $this->translate('submit') ?></a></div>

                        </form>
                    </div>
                
                </div>
            </div>
        </div>
    </div>
</div>
<div id="form-errors"><ul><ul></div>

<script type="text/javascript">
$(document).ready(function(){
    $("#form-errors").hide().fadeIn(4000);
    $('#btnResetPassword').click(function(e) {
        
        $('.ajax-loader').show();
        $(this).attr("disabled", "disabled"); 
        
        $.ajax({
            type: "post",
            dataType: "json",
            url: "/users/validate-password", 
            data: {'password': $('#password').val(), 'confirm_password': $('#confirm_password').val() },
            success: function(res) {
                
                 $('#btnResetPassword').removeAttr('disabled');
                $('.ajax-loader').hide();
                
                if (res.success == true) {
                   $('#reset-password-form').submit();
                } else {
                    outputFormErrorMessages(res);
                }
            }
        });
        return false;
    });
    
    $('#form-errors').dialog({
        autoOpen: false,
        modal: true,
        title: '<?php echo $this->translate('reset_password') ?>',
        width: 500,
        show: { effect: 'fade', duration: 500 },
        hide: { effect: 'hide', duration: 500 },
        buttons: {
            '<?php echo $this->translate('close') ?>': function(){
                $(this).dialog("close");
            }
        }
    });
});

function outputFormErrorMessages(response) {
    $('#form-errors ul').empty();
    $('input').removeClass('error');
    $.each(response, function (k, v) {
        $.each(v, function(k1, v1) {
            $('#form-errors ul').append('<li>' + '<?php echo $this->translate('email') ?>' + ': ' + v1 + '</li>');
            $('#' + k).addClass('error');
        });
    });
    $('#form-errors').dialog('open');
}
</script>
