<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users">My PROFILE</a></li>
                <li class="active"><a href="/event/agenda">AGENDA</a></li>
                <li><a href="/event/conf">CONFERENCE Speakers & Venue</a></li>
                <li><a href="/event/hospitality">HOSPITALITY</a></li>
                <li><a href="/event/contact">CONTACT & RSVP</a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>">Logout</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">AGENDA</div>
        <div id="venue">
            <table width="100%">
                <tr><th width="25%"></th><th></th></tr>
                <tr><td>Venue Name</td><td>Venue Name Detail</td></tr>
                <tr><td>Venue Addr</td><td>Venue Addr Detail</td></tr>
                <tr><td>Venue Hours</td><td>Hours Detail</td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Contact Information</td><td>Tel 155 555 555 555</td></tr>
                <tr><td></td><td>email lorem@ipsum.com</td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Agenda of the day</td><td>Tel 155 555 555 555</td></tr>
                <tr><td></td><td>email lorem@ipsum.com</td></tr>
            </table>
        </div>
    </div>
    
</div>