<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li class="active"><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        
        <div id="main-content-title"><?php echo $this->translate('agenda') ?></div>
        
        <div id="agenda">

            <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>
            
                <div class="block">
                     <div class="block-title">PROGRAM</div>
                     <div class="sub-block">
                         <label class="sub-block-title underlined">Monday April 8th 2013</label>
                         <ul>
                            <li><span>Morning:</span></li>
                            <li>09:00 – 11:00: Arrivals / Hotel Check-in</li>
                            <li>11.00 – 12.00: Lunch time at Café 1188 (Hotel 1st floor)</li>
                        </ul>
                        <ul>
                            <li><span>Afternoon: Shanghai Expo Centre</span> 1500 Expo Avenue Pudong  District, Shanghai, China</li>
                            <li>12:00 – 13:00: Transfer to the Conference for Registration</li>
                            <li>13:00 – 16:30: Conference</li>
                            <li>16:30 – 17:00: Transfer to the Hotel</li>
                            <li>17:00 – 18:00: Break Time</li>
                            <li>18:00 – 18:30: Transfer to the Dinner</li>
                        </ul>
                        <ul>
                            <li><span>Evening: Shanghai Expo Centre</span> 1500 Expo Avenue Pudong  District, Shanghai, China</li>
                            <li>18:30 – 21:30: Gala Dinner</li>
                            <li>21:30: Transfer to the Hotel</li>
                        </ul>
                        <ul><li><span>Overnight at Intercontinental Expo Hotel</span></li></ul>
                     </div>
                     <div class="sub-block">
                        <label class="sub-block-title underlined">Monday April 8th 2013</span></label>
                        <ul>
                            <li>06:30 – 10:00: Breakfast</li>
                            <li>06:30 – 12:00: Departures</li>
                        </ul>
                     </div>
                </div>
        
                
        
            <?php } else { ?>
        
                <div class="block">
                    <div class="block-title">会议日程</div>
                    <div class="sub-block">
                        <label class="sub-block-title underlined">2013年4月8日 星期一</label>
                        <ul>
                            <li><span>早晨：</span>上海世博洲际酒店</li>
                            <li>09:00 – 11:00: 到达/酒店登记</li>
                            <li>11.00 – 12.00: 午餐  咖啡厅1188 (酒店1楼)</li>
                        </ul>
                        <ul>
                            <li><span>下午：上海世博中心</span>  浦东新区世博大道1500号</li>
                            <li>12:00 – 13:00: 会议签到</li>
                            <li>13:00 – 16:30: 会议</li>
                            <li>16:30 – 17:00: 返回酒店</li>
                            <li>17:00 – 18:00: 休息</li>
                            <li>18:00 – 18:30: 返回会场</li>
                        </ul>
                        <ul>
                            <li><span>晚上：上海世博中心</span>  浦东新区雪野路1188号</span></li>
                            <li>18:30 – 21:30: 晚宴</li>
                            <li>21:30: 下榻世博洲际酒店</li>
                        </ul>
                    </div>

                    <div class="sub-block">
                        <label class="sub-block-title underlined">2013年4月9日 星期二</label>
                        <ul>
                            <li>06:30 – 10:00: 早餐</li>
                            <li>06:30 – 12:00: 返程</li>
                        </ul>
                    </div>
                </div>

                
      
            <?php } ?>

        </div>
        <div class="clear"></div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    <?php if (count($this->success_messages)) { ?>
            alert('<?php echo $this->success_messages['0'] ?>');
            <?php } ?>
});
</script>