<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users">My Profile</a></li>
                <li><a href="/event/venue">Venue Information</a></li>
                <li class="active"><a href="/event/conf-lib">Conference Library</a></li>
                <li><a href="/event/gallery">Gallery</a></li>
                <li><a href="/event/survey">Survey</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">Conference Library</div>
        <div id="conf-lib">
        
            <div class="block">
                <label>Sales</label>
                <ul>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                </ul>
            </div>
        
            <div class="block">
                <label>Marketing</label>
                <ul>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                </ul>
            </div>
        
            <div class="block">
                <label>Guidelines</label>
                <ul>
                    <li>
                        <span>Lorem 2 ipsum world sales PDF doc</span>
                        <span>April 1st 2013</span>
                        <span><a href="" class="small-btn">Download</a></span>
                    </li>
                </ul>
            </div>
       
        </div>
    </div>
    
</div>