<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li class="active"><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/survey"><?php echo $this->translate('survey') ?></a></li>
                <li><a href="/event/photowall"><?php echo $this->translate('photowall') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('conference_speakers') ?></div>
        
        <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>
                
																																							 <div class="block-title">CONFERENCE SPEAKERS</div>
																																							 <table width="100%">
																																							 <tr>
																																							 <td width="50%" valign="top">

																																							 <table border="0">
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Bob_Grace.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">Bob Grace,<br/>President<br><br>Topic : JLRC Welcome and Introduction</div></td>
																																							 </tr>
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Bruce_Robertson.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">Bruce Robertson,<br/>Executive Vice President Operations<br><br>Topic : Sales Operations</div></td>
																																							 </tr>
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/RV.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">Ricardo Viana,<br/>Executive Vice President After Sales<br><br>Topic : After Sales</div></td>
																																							 </tr>
																																							 
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Nick_Wang.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">Nick Wang,<br/>Chief Financial Officer, Executive Vice President<br><br>Topic : Finance Services</div></td>
																																							 </tr>
                                                                                    <tr>                                                                                                                                                                                                                                                              <td><img src="/medias/images/uploads/speakers/Crystal_Gu.jpg" width="150" height="150" border="0"></td>                                                                                                                                                        <td style="padding-left:10px"><div class="sub-block full">Crystal Gu,<br/>Vice President Communication<br><br>Topic : PR Activities</div></td>
                                                              </tr>                                                                                                                                                                                                                                                            <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Lily_Song.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">Lily Song,<br/>Vice President Land Rover Marketing Communication<br><br>Topic : Land Rover Brand</div></td>
																																							 </tr>
																																							 </table>
																																							 </td>

																																							 <td width="50%" valign="top">
																																							 <table border="0">

																																							 <tr><td colspan="2" height="150">&nbsp;</td></tr>                                                                                                                                                                                                                                                                                                                            <tr>
                                                                <td><img src="/medias/images/uploads/speakers/Vincent_Yan.jpg" width="150" height="150" border="0"></td>
                                                                <td style="padding-left:10px"><div class="sub-block full">Vincent Yan,<br/>Vice President National Sales<br><br>Topic : Sales Operations</div></td>
																														 </tr>
                                                                                                                                                                                                                                                                                                                            <tr>
																															 <td><img src="/medias/images/uploads/speakers/Roger_Gu.jpg" width="150" height="150" border="0"></td>
                                                                <td style="padding-left:10px"><div class="sub-block full">Roger Gu,<br/>Vice President Customer Service Commericial<br><br>Topic : After Sales</div></td>                                                                                                    </tr>
                                                               
                                                             <tr><td colspan="2" height="150">&nbsp;</td></tr>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>                                                                                                                                                                                                                                                             <td><img src="/medias/images/uploads/speakers/May_Che.jpg" width="150" height="150" border="0"></td>
																															 <td style="padding-left:10px"><div class="sub-block full">May Che,<br/>Executive Vice President Jaguar Brand China<br><br>Topic : Jaguar Brand</div></td>
																														 </tr>

                                                                                                                                                                                                                                                                                                                            <tr>
                                                                <td><img src="/medias/images/uploads/speakers/Anthony_Bradbury.jpg" width="150" height="150" border="0"></td>
                                                                <td style="padding-left:10px"><div class="sub-block full">Anthony Bradbury,<br/>Executive Vice President Land Rover Brand China<br><br>Topic : Land Rover Brand</div></td>
                                                              </tr>
																																							 <tr>
																																							 </tr>
																																							 </table>

																																							 </td>
																																							 </tr>
																																							 </table>

               
        <?php } else { ?>


	 <div class="block-title">大会演讲嘉宾</div>
																																							 <table width="100%">
																																							 <tr>
																																							 <td width="50%" valign="top">

																																							 <table>
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Bob_Grace.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">高博<br/>总裁<br><br>演讲主题：欢迎致辞</div></td>
																																							 </tr>
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Bruce_Robertson.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">罗伯逊<br/>运营执行副总裁<br><br>演讲主题：销售运营</div></td>
																																							 </tr>
																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/RV.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">维嘉德<br/>售后服务执行副总裁<br><br>演讲主题：售后服务</div></td>
																																							 </tr>

																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Nick_Wang.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">汪冬宁<br/>首席财务官 执行副总裁<br><br>演讲主题：财政战略</div></td>
																																							 </tr>
                                                                                                                                                                                                                        <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Crystal_Gu.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">谷晶<br/>捷豹路虎中国公关关系副总裁<br><br>演讲主题：公关活动</div></td>
																																							 </tr>                                                                                                                                                                                                                                       <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Lily_Song.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">宋丽丽<br/>路虎中国市场副总裁<br><br>演讲主题：路虎品牌</div></td>
																																							 </tr>
																																							 </table>
																																							 </td>

																																							 <td width="50%" valign="top">
																																							 <table>
																																							 <tr><td colspan="2" height="150">&nbsp;</td></tr>

																																							                                                                                                                                                                                                                                 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Vincent_Yan.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">闫丞君<br/>销售副总裁<br><br>演讲主题：销售运营</div></td>
																																							 </tr>
                                                                                                                                                                                                                                                                                                                         <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Roger_Gu.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">顾万国<br/>售后商务副总裁<br><br>演讲主题：售后服务</div></td>
																																							 </tr>
                                                                           																																							 <tr><td colspan="2" height="150">&nbsp;</td></tr>
                                                                                   <tr>
																																							 <td><img src="/medias/images/uploads/speakers/May_Che.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">车艳华<br/>捷豹中国市场执行副总裁<br><br>演讲主题：捷豹品牌</div></td>
																																							 </tr>
                                                                                                              


																																							 <tr>
																																							 <td><img src="/medias/images/uploads/speakers/Anthony_Bradbury.jpg" width="150" height="150" border="0"></td>
																																							 <td style="padding-left:10px"><div class="sub-block full">柏睿安<br/>路虎中国市场执行副总裁<br><br>演讲主题：路虎品牌</div></td>
																																							 </tr>
																																							 </table>

																																							 </td>
																																							 </tr>
																																							 </table>

    
                     
        <?php } ?>
        <div class="clear"></div>
    </div>
</div>
