<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/survey"><?php echo $this->translate('survey') ?></a></li>
                <li><a href="/event/photowall"><?php echo $this->translate('photowall') ?></a></li>
                <li class="active"><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('contact') ?></div>
        
        <div id="contact">
            
            <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>

                <div class="block">
                    <div class="sub-block full">
                        <ul><li>If you need any information regarding this event, please contact our team:</li></ul>
                        <ul>
                            <li><span>Email:</span> <a href="mailto:registration@2013-jlrc-conference.com">registration@2013-jlrc-conference.com</a></li>
                            <li><span> number:</span> 021 6258 5325 // 62585320   Working hours: 09:30 – 18:30</li>
                            <li><span>Emergency number：</span>135 5015 6344  (Available from April 7th to April 9th / 24hours service)</li>
                        </ul>
                        <ul>
                            <li>A maximum of 2 guests per dealership will be attend the conference and gala dinner.</li>
                            <li>If you want to invite an additional guest, please directly contact your respective area business manager.</li>
                        </ul>
                    </div>
                </div>
               
            
                <div class="block">
                     <div class="block-title">IMPORTANT NOTES</div>
                     <ul class="decimal">
                         <li>All attendees are to stay at this event hotel Intercontinental Shanghai Expo hotel on April 8th if hotel accommodation is required.</li>
                         <li>Guaranteed are a number of rooms available at a special rate of 1,100 RMB net per night.</li>
                         <li>Lunch is provided at the Intercontinental hotel on April 8th.</li>
                         <li>Guests not staying at the Intercontinental Hotel are expected to arrange their break venue and transfers independently on April 8th 16:30 – 18:30, but must return the conference venue to attend the gala dinner.</li>
                         <li>Your ID card or passport is required for conference access.</li>
                         <li>Dress Code: Formal attire</li>
                         <li>No cameras allowed during the event.</li>
                    </ul>
                </div>
        
            <?php } else { ?>
            
                <div class="block">
                    <div class="sub-block full">
                        <ul><li>若您对有任何疑问，请及时联系我们：</li></ul>
                        <ul>
                            <li><span>Email: </span><a href="mailto:registration@2013-jlrc-conference.com">registration@2013-jlrc-conference.com</a></li>
                            <li><span>热线电话：</span>021 6258 5325 // 62585320   工作时间：09:30 – 18:30</li>
                            <li><span>紧急电话：</span>135 5015 6344  从4月7日至4月9日 24小时服务</li>
                        </ul>
                        <ul>
                            <li>每位经销商最多限2人参加此次大会和晚宴。</li>
                            <li>如果你想邀请更多人员，请向捷豹路虎中国相关人员申请。</li>
                        </ul>
                    </div>
                </div>

                <div class="block">
                    <div class="block-title">重要提醒</div>
                    <ul class="decimal">
                        <li>所有需要住宿的宾客必须入住本次会议指定酒店：上海世博洲际酒店</li>
                        <li>捷豹路虎中国已与酒店商定本次会议特别价，即1100元/每晚</li>
                        <li>4月8日当天在上海世博洲际酒店提供自助午餐</li>
                        <li>个别不需要住宿的宾客，须自行安排4月8日当天16：30 -18：30的休息地点和相关交通，但必须于18：30前返回会场参加晚宴。</li>
                        <li>宾客须出示身证份或护照方可允许进入会议现场</li>
                        <li>着装要求：正装</li>
                        <li>会议期间禁止摄影摄像</li>
                    </ul>
                </div>
                
            <?php } ?>
        </div>
    </div>
</div>
