<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users">My PROFILE</a></li>
                <li><a href="/event/agenda">AGENDA</a></li>
                <li><a href="/event/conf">CONFERENCE Speakers & Venue</a></li>
                <li><a href="/event/hospitality">HOSPITALITY</a></li>
                <li class="active"><a href="/event/contact">CONTACT & RSVP</a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>">Logout</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">CONTACT</div>
        <div id="survey">
       
        </div>
    </div>
</div>