<div class="event">
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users">My Profile</a></li>
                <li><a href="/event/venue">Venue Information</a></li>
                <li><a href="/event/conf-lib">Conference Library</a></li>
                <li class="active"><a href="/event/gallery">Gallery</a></li>
                <li><a href="/event/survey">Survey</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">Gallery</div>
        <div id="gallery">
       
        </div>
    </div>
</div>