<div class="users">
    
    <div id="navigation">
        <ul>
            <li class="first"><a href="/users">My Profile</a></li>
            <li><a href="/event/venue">Venue Information</a></li>
            <li><a href="/event/conf-lib">Conference Library</a></li>
            <li class="active"><a href="/event/gallery">Gallery</a></li>
            <li><a href="/event/survey">Survey</a></li>
        </ul>
    </div>
    
    <div id="profile">
       
    </div>
</div>