<div class="event">
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li class="active"><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('hospitality') ?></div>
        <div id="hospitality">
            <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>
            <div class="full">
                <div class="half-width f-left">
                    <div class="block">
                        <div class="block-title">HOTEL INFORMATION</div>
                        <ul class="disc" style="width: 400px;">
                            <li>InterContinental Shanghai Expo is Shanghai’s newest luxury hotel</li>
                            <li>Located on the Pudong side of the Nanpu Bridge</li>
                            <li>40 minutes by car from Pudong International Airport</li>
                            <li>30 minutes from Hongqiao Airport</li>
                            <li>8 minutes to Lujiazui, Shanghai business centre</li>
                            <li>10 minutes to Xintiandi</li>
                            <li>Spectacular views of Shanghai Expo China Pavilion, Huangpu River and the city skyline</li>
                            <li>Metro stations 4, 6, 7 and 8 are nearby</li>
                            <li>Hotel is close to all city attractions in Puxi and Pudong</li>
                        </ul>
                    </div>
            
                    <div class="block">
                        <div class="block-title">WHAT'S NEARBY</div>
                        <ul style="width: 400px;">
                            <li>China Pavilion </li>
                            <li>World Expo Centre</li>
                            <li>Mercedes Benz Arena </li>
                            <li>The Bund</li>		
                            <li>Yu Yuan Gardens</li>
                            <li>Old French Concession</li>
                            <li>Oriental Pearl Tower </li>
                            <li>Gift Market </li>	
                            <li>Fabric Market</li>
                            <li>People’s Square </li>
                            <li>Century Park</li>		
                            <li>Shanghai New International Expo Centre </li>
                            <li>Shanghai Museum</li>
                            <li>Xintiandi </li>
                            <li>Shanghai Science & Technology Museum</li>
                        </ul>
                    </div>
                </div>  
                <div class="half-width f-right">
                    <div class="block">
                        <div id="hotel-image"> <img src="/medias/images/hotel.jpg" width="500"/></div>
                    </div>
                </div>
            </div>
           
            
            <div class="block">
                <div class="block-title">HOTEL ROOMS</div>
                <div class="sub-block">
 <table>
<tr>
<td><div>Single Room</div></td>
<td><div>Twin Room</div></td>
</tr>
<tr>
<td><img src="/medias/images/hotel_single_room.jpg"></td>
<td><img src="/medias/images/hotel_twin_room.jpg"></td>
</tr>
</table>
                </div>
            </div>     
            
            <div class="block">
                <div class="block-title">HOTEL MAPS</div>
                <div class="sub-block"><div id="hotel-map-detail"><iframe width="700" height="350" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?oe=utf-8&amp;client=firefox-a&amp;ie=UTF8&amp;q=intercontinental+shanghai+pudong&amp;fb=1&amp;hq=intercontinental&amp;hnear=0x35ad8c73cd3952c7:0xbb190e9364c4e592,District+de+Pudong,+Shanghai,+R%C3%A9publique+populaire+de+Chine&amp;cid=0,0,17926781966426129906&amp;ll=31.229573,121.521663&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe></div></div>
            </div>  
            
            <div class="block">
                <div class="block-title">TRANSFERS</div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Hongqiao+Airport+Terminal+1,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.191178,121.348391&sspn=0.010426,0.01929&geocode=FYrw2wEdJ6E7Byk1LJeAm2ayNTFH6C--ytT_Kw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Intercontin&mra=ls&t=m&z=12">From Hongqiao airport</a></label><div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&ie=UTF8&ll=31.17051,121.647491&spn=0.166854,0.308647&sll=31.193605,121.432689&sspn=0.166813,0.308647&geocode=FeyE2wEdi39CByHku9n2TQ4s6Sn1jyGq24-tNTHku9n2TQ4s6Q%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Pudong&mra=ls&t=m&z=12">From Pudong airport</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+Railway+Station,+Jiaotong+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.17051,121.647491&sspn=0.166854,0.308647&geocode=FYbR3AEda0I9BynNpqa9JXCyNTFqrQyVfci6oQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+RAilwa&mra=ls&t=m&z=13">From Shanghai railway station</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+South+Railway+Station,+Dongli+North+1st+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&ll=31.181819,121.473083&spn=0.083417,0.154324&sll=31.224769,121.484426&sspn=0.083379,0.154324&geocode=FZZc2wEd7908BylFpsOWvGSyNTGYNitMfU3Uyw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+South+Railway+Station&mra=ls&t=m&z=13">From Shanghai south railway station</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+West+Railway+Station,+Taopu+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.181819,121.473083&sspn=0.083417,0.154324&geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+West+Railway+Station&mra=ls&t=m&z=12">From Shanghai west railway station</a></label></div>
                </div>

            <div class="block"><div class="block-title"><a href="/medias/pdf/intercontinental-en.pdf" target="new">PDF WITH HOTEL INFORMATION TO DOWNLOAD HERE (English version)</a></div></div>
            
            <div class="clear"></div>
            <?php } else { ?>
            <div class="full">
                <div class="half-width f-left">
                    <div class="block">
                        <div class="block-title">酒店信息</div>
                        <ul class="disc" style="width: 400px;">
                            <li>上海世博洲际酒店是上海最新的奢华型五星级酒店 </li>
                            <li>酒店座落于南浦大桥堍，黄浦江畔，拥有极佳的地理位置 </li>
                            <li>距离浦东国际机场仅需40分钟车程</li>
                            <li>距离虹桥机场仅需30分钟车程</li>
                            <li>距离陆家嘴商圈仅需8分钟车程</li>
                            <li>到达新天地仅需10分钟车程</li>
                            <li>从酒店您可以欣赏中国馆和文化中心，无与伦比的城市天际线及流光溢彩的浦江美景</li>
                            <li>酒店附近有4号线、6号线、7号线和8号线</li>
                            <li>从酒店前往浦西和浦东的各城市景点均十分便捷</li>
                        </ul>
                    </div>
            
                    <div class="block">
                        <div class="block-title">酒店附近</div>
                        <ul style="width: 400px;">
                            <li>中国馆</li>
                            <li>世博中心  </li>
                            <li>梅赛德斯奔驰文化中心</li>
                            <li>外滩</li>		
                            <li>豫园</li>
                            <li>法租界</li>
                            <li>东方明珠</li>
                            <li>礼品市场	</li>	
                            <li>面料市场</li>
                            <li>人民广场	</li>
                            <li>世纪公园	</li>		
                            <li>上海新国际博览中心</li>
                            <li>上海博物馆</li>
                            <li>新天地</li>
                            <li>上海科技馆</li>
                        </ul>
                    </div>
                </div>  
                <div class="half-width f-right">
                    <div class="block">
                        <div id="hotel-image"> <img src="/medias/images/hotel.jpg" width="500"/></div>
                    </div>
                </div>
            </div>
            
            <div class="block">
                <div class="block-title">酒店客房</div>
                <div class="sub-block">

 <table>
<tr>
<td><div>单人房</div></td>
<td><div>双人房</div></td>
</tr>
<tr>
<td><img src="/medias/images/hotel_single_room.jpg"></td>
<td><img src="/medias/images/hotel_twin_room.jpg"></td>
</tr>
</table>
                </div>
            </div>     
            
            <div class="block">
                <div class="block-title">酒店地图</div>
                <div class="sub-block"><div id="hotel-map-detail"><iframe width="700" height="350" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?oe=utf-8&amp;client=firefox-a&amp;ie=UTF8&amp;q=intercontinental+shanghai+pudong&amp;fb=1&amp;hq=intercontinental&amp;hnear=0x35ad8c73cd3952c7:0xbb190e9364c4e592,District+de+Pudong,+Shanghai,+R%C3%A9publique+populaire+de+Chine&amp;cid=0,0,17926781966426129906&amp;ll=31.229573,121.521663&amp;spn=0.006295,0.006295&amp;t=m&amp;output=embed"></iframe></div></div>
            </div>  
            
            <div class="block">
                <div class="block-title">交通信息</div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Hongqiao+Airport+Terminal+1,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.191178,121.348391&sspn=0.010426,0.01929&geocode=FYrw2wEdJ6E7Byk1LJeAm2ayNTFH6C--ytT_Kw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Intercontin&mra=ls&t=m&z=12">从上海虹桥机场</a></label><div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&ie=UTF8&ll=31.17051,121.647491&spn=0.166854,0.308647&sll=31.193605,121.432689&sspn=0.166813,0.308647&geocode=FeyE2wEdi39CByHku9n2TQ4s6Sn1jyGq24-tNTHku9n2TQ4s6Q%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Pudong&mra=ls&t=m&z=12">从上海浦东机场</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+Railway+Station,+Jiaotong+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.17051,121.647491&sspn=0.166854,0.308647&geocode=FYbR3AEda0I9BynNpqa9JXCyNTFqrQyVfci6oQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+RAilwa&mra=ls&t=m&z=13">从上海火车站</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+South+Railway+Station,+Dongli+North+1st+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&ll=31.181819,121.473083&spn=0.083417,0.154324&sll=31.224769,121.484426&sspn=0.083379,0.154324&geocode=FZZc2wEd7908BylFpsOWvGSyNTGYNitMfU3Uyw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+South+Railway+Station&mra=ls&t=m&z=13">从上海南站</a></label></div>
                <div class="sub-block half-width"><label><a href="https://maps.google.fr/maps?saddr=Shanghai+West+Railway+Station,+Taopu+Road,+Shanghai,+Chine&daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&hl=fr&sll=31.181819,121.473083&sspn=0.083417,0.154324&geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&oq=Shanghai+West+Railway+Station&mra=ls&t=m&z=12">从上海西站</a></label></div>
                </div>
            </div>
            
            <div class="block"><div class="block-title"><a href="/medias/pdf/intercontinental-zh.pdf" target="new">请在这里下载酒店信息PDF (英文版)</a></div></div>
                
            <div class="clear"></div>
            <?php } ?>
        </div>
    </div>
</div>
