<div class="event">
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li class="active"><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/survey"><?php echo $this->translate('survey') ?></a></li>
                <li><a href="/event/photowall"><?php echo $this->translate('photowall') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('hospitality') ?></div>
        <div id="hospitality">
            <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>
            <div class="full">
                <div class="half-width f-left">
                    <div class="block">
                        <div class="block-title">HOTEL</div>
                        <div class="sub-block">
                            <label class="sub-block-title">HOTEL INFORMATION</label>
                            <ul>
                                <li><span>Telephone: </span> +86 (0)21 3858 1188</li>
                                <li><span>Address: </span> 1188 Xueye Road, Pudong Shanghai </li>
                                <li><span>Website: </span> <a href="www.intercontinental.com">www.intercontinental.com</a></li>
                            </ul>
                            <ul class="disc" style="width: 400px;">
                                <li>InterContinental Shanghai Expo is Shanghai’s newest luxury hotel</li>
                                <li>Located on the Pudong side of the Nanpu Bridge</li>
                                <li>40 minutes by car from Pudong International Airport</li>
                                <li>30 minutes from Hongqiao Airport</li>
                                <li>8 minutes to Lujiazui, Shanghai business centre</li>
                                <li>10 minutes to Xintiandi</li>
                                <li>Spectacular views of Shanghai Expo China Pavilion, Huangpu River and the city skyline</li>
                                <li>Metro stations 4, 6, 7 and 8 are nearby</li>
                                <li>Hotel is close to all city attractions in Puxi and Pudong</li>
                            </ul>
                        </div>
                     </div>
                </div>  
                <div class="half-width f-right">
                    <div class="block">
                        <div id="hotel-image"> <img src="/medias/images/hotel.jpg" width="500"/></div>
                    </div>
                </div>
            </div>
           
            
            <div class="block">
                <div class="block-title">HOTEL ROOMS</div>
                <div class="sub-block">
                    <table>
                   <tr>
                   <td><div>Single Room</div></td>
                   <td><div>Twin Room</div></td>
                   </tr>
                   <tr>
                   <td><img src="/medias/images/hotel_single_room.jpg"></td>
                   <td><img src="/medias/images/hotel_twin_room.jpg"></td>
                   </tr>
                   </table>
                                   </div>
            </div>     
            
            <div class="block">
                <div class="block-title">HOTEL MAPS</div>
                <div class="sub-block"><div id="hotel-map-detail">
<iframe width="700" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?q=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E9%9B%AA%E9%87%8E%E8%B7%AF1188%E5%8F%B7&amp;ie=UTF8&amp;hq=&amp;hnear=Shanghai+Kailuoze+Management+Continuing+Education+College,+124%E5%8F%B7+Yong+Ye+Lu,+Pu+Dong+Xin+Qu,+Shanghai&amp;t=m&amp;brcurrent=3,0x35b27a4f25879eb1:0xbd6cd4370b6f9c12,0,0x35ad8c73cd3952c7:0xbb190e9364c4e592%3B5,0,0&amp;ll=31.189308,121.504283&amp;spn=0.012849,0.030041&amp;z=15&amp;output=embed"></iframe>                    </div></div>
            </div>  
            
            <div class="block">
                <div class="block-title">TRANSFERS</div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_1">From Hongqiao airport</label></a><div class="iframe" id="iframe_1"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Hongqiao+Airport+Terminal+1,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.191178,121.348391&amp;sspn=0.010426,0.01929&amp;geocode=FYrw2wEdJ6E7Byk1LJeAm2ayNTFH6C--ytT_Kw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Intercontin&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;vpsrc=0&amp;ll=31.193605,121.432689&amp;spn=0.031161,0.169007&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_2">From Pudong airport</label></a><div class="iframe" id="iframe_2"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;ie=UTF8&amp;sll=31.193605,121.432689&amp;sspn=0.166813,0.308647&amp;geocode=FeyE2wEdi39CByHku9n2TQ4s6Sn1jyGq24-tNTHku9n2TQ4s6Q%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Pudong&amp;mra=ls&amp;t=m&amp;vpsrc=0&amp;ll=31.17051,121.647491&amp;spn=0.166854,0.308647&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label  class="transfer" id="transfer_3">From Shanghai railway station</label></a><div class="iframe" id="iframe_3"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+Railway+Station,+Jiaotong+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.17051,121.647491&amp;sspn=0.166854,0.308647&amp;geocode=FYbR3AEda0I9BynNpqa9JXCyNTFqrQyVfci6oQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+RAilwa&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;ll=31.224839,121.484413&amp;spn=0.051378,0.082397&amp;z=13&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_4">From Shanghai south railway station</label></a><div class="iframe" id="iframe_4"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+South+Railway+Station,+Dongli+North+1st+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.224769,121.484426&amp;sspn=0.083379,0.154324&amp;geocode=FZZc2wEd7908BylFpsOWvGSyNTGYNitMfU3Uyw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+South+Railway+Station&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;ll=31.181819,121.473083&amp;spn=0.051401,0.072784&amp;z=13&amp;output=embed"></iframe></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_5">From Shanghai west railway station</label></a><div class="iframe" id="iframe_5"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+West+Railway+Station,+Taopu+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.181819,121.473083&amp;sspn=0.083417,0.154324&amp;geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+West+Railway+Station&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;vpsrc=0&amp;ll=31.219956,121.456854&amp;spn=0.083864,0.120676&amp;output=embed"></iframe></div></div>
            </div>

            <div class="block"><div class="block-title"><a href="/medias/pdf/intercontinental-en.pdf" target="new">PDF WITH HOTEL INFORMATION TO DOWNLOAD HERE (English version)</a></div></div>
            
            <div class="clear"></div>
            <?php } else { ?>
            <div class="full">
                <div class="half-width f-left">
                    <div class="block">
                       
                        <div class="block-title">酒店</div>
                        <div class="sub-block">
                            <label class="sub-block-title">酒店信息</label>
                            <ul>
                                <li><span>电话: </span> +86 (0)21 3858 1188</li>
                                <li><span>地址: </span> 上海浦东新区雪野路1188号 </li>
                                <li><span>网址: </span> <a href="www.intercontinental.com">www.intercontinental.com</a></li>
                            </ul>
                        <ul class="disc" style="width: 400px;">
                            <li>上海世博洲际酒店是上海最新的奢华型五星级酒店 </li>
                            <li>酒店座落于南浦大桥堍，黄浦江畔，拥有极佳的地理位置 </li>
                            <li>距离浦东国际机场仅需40分钟车程</li>
                            <li>距离虹桥机场仅需30分钟车程</li>
                            <li>距离陆家嘴商圈仅需8分钟车程</li>
                            <li>到达新天地仅需10分钟车程</li>
                            <li>从酒店您可以欣赏中国馆和文化中心，无与伦比的城市天际线及流光溢彩的浦江美景</li>
                            <li>酒店附近有4号线、6号线、7号线和8号线</li>
                            <li>从酒店前往浦西和浦东的各城市景点均十分便捷</li>
                        </ul>
                    </div>
                    </div>
                    
                </div>  
                <div class="half-width f-right">
                    <div class="block">
                        <div id="hotel-image"> <img src="/medias/images/hotel.jpg" width="500"/></div>
                    </div>
                </div>
            </div>
            
            <div class="block">
                <div class="block-title">酒店客房</div>
                <div class="sub-block">

                        <table>
                       <tr>
                       <td><div>单人房</div></td>
                       <td><div>双人房</div></td>
                       </tr>
                       <tr>
                       <td><img src="/medias/images/hotel_single_room.jpg"></td>
                       <td><img src="/medias/images/hotel_twin_room.jpg"></td>
                       </tr>
                       </table>
                </div>
            </div>     
            
            <div class="block">
                <div class="block-title">酒店地图</div>
                <div class="sub-block"><div id="hotel-map-detail">
<iframe width="700" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?q=%E4%B8%8A%E6%B5%B7%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E9%9B%AA%E9%87%8E%E8%B7%AF1188%E5%8F%B7&amp;ie=UTF8&amp;hq=&amp;hnear=Shanghai+Kailuoze+Management+Continuing+Education+College,+124%E5%8F%B7+Yong+Ye+Lu,+Pu+Dong+Xin+Qu,+Shanghai&amp;t=m&amp;brcurrent=3,0x35b27a4f25879eb1:0xbd6cd4370b6f9c12,0,0x35ad8c73cd3952c7:0xbb190e9364c4e592%3B5,0,0&amp;ll=31.189308,121.504283&amp;spn=0.012849,0.030041&amp;z=15&amp;output=embed"></iframe>                    </div></div>
            </div>  
            
            <div class="block">
                <div class="sub-block full"><label class="sub-block-title" style="font-size: 18px; width:100%;">交通信息</label></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_1">从上海虹桥国际机场</label></a><div class="iframe" id="iframe_1"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Hongqiao+Airport+Terminal+1,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.191178,121.348391&amp;sspn=0.010426,0.01929&amp;geocode=FYrw2wEdJ6E7Byk1LJeAm2ayNTFH6C--ytT_Kw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Intercontin&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;vpsrc=0&amp;ll=31.193605,121.432689&amp;spn=0.031161,0.169007&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_2">从上海浦东国际机场</label></a><div class="iframe" id="iframe_2"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;ie=UTF8&amp;sll=31.193605,121.432689&amp;sspn=0.166813,0.308647&amp;geocode=FeyE2wEdi39CByHku9n2TQ4s6Sn1jyGq24-tNTHku9n2TQ4s6Q%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Pudong&amp;mra=ls&amp;t=m&amp;vpsrc=0&amp;ll=31.17051,121.647491&amp;spn=0.166854,0.308647&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label  class="transfer" id="transfer_3">从上海火车站</label></a><div class="iframe" id="iframe_3"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+Railway+Station,+Jiaotong+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.17051,121.647491&amp;sspn=0.166854,0.308647&amp;geocode=FYbR3AEda0I9BynNpqa9JXCyNTFqrQyVfci6oQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+RAilwa&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;ll=31.224839,121.484413&amp;spn=0.051378,0.082397&amp;z=13&amp;output=embed"></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_4">从上海南站</label></a><div class="iframe" id="iframe_4"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+South+Railway+Station,+Dongli+North+1st+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.224769,121.484426&amp;sspn=0.083379,0.154324&amp;geocode=FZZc2wEd7908BylFpsOWvGSyNTGYNitMfU3Uyw%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+South+Railway+Station&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;ll=31.181819,121.473083&amp;spn=0.051401,0.072784&amp;z=13&amp;output=embed"></iframe></iframe></div></div>
                <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_5">从上海西站</label></a><div class="iframe" id="iframe_5"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.fr/maps?saddr=Shanghai+West+Railway+Station,+Taopu+Road,+Shanghai,+Chine&amp;daddr=Intercontinental+Shanghai+Expo,+Xueye+Road,+District+de+Pudong,+Shanghai,+Chine&amp;hl=fr&amp;sll=31.181819,121.473083&amp;sspn=0.083417,0.154324&amp;geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUYZ3AEd-gg-ByGv-84QNIDIVSmZpTQfd3qyNTGv-84QNIDIVQ&amp;oq=Shanghai+West+Railway+Station&amp;mra=ls&amp;t=m&amp;ie=UTF8&amp;vpsrc=0&amp;ll=31.219956,121.456854&amp;spn=0.083864,0.120676&amp;output=embed"></iframe></div></div>
            </div>
            
            <div class="block"><div class="block-title"><a href="/medias/pdf/intercontinental-zh.pdf" target="new">请在这里下载酒店信息PDF (英文版)</a></div></div>
                
            <div class="clear"></div>
            <?php } ?>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function() {
    $('label.transfer').click(function(){
        var id = ($(this).attr('id').split('_'))['1'];
   
        if ($('#iframe_'+id).is(":visible") )
            $('#iframe_' + id).slideUp();
        else 
            $('#iframe_' + id).slideDown();
        return false;
    });
});
</script>