<div class="event">
    
    <div id="navigation">
        <ul>
            <li class="first"><a href="/users">My Profile</a></li>
            <li class="active"><a href="/event/venue">Venue Information</a></li>
            <li><a href="/event/conf-lib">Conference Library</a></li>
            <li><a href="/event/gallery">Gallery</a></li>
            <li><a href="/event/survey">Survey</a></li>
        </ul>
    </div>
    
    <div id="venue">
        <div class="left">
            <div class="block">
                <label>Venue Name</label>
                <div>
                    <div>Venue Address</div>
                    <div>Hours</div>
                </div>
            </div>

            <div class="block">
                <label>Contact information</label>
                <div>
                    <div>Tel 155 555 555 555</div>
                    <div>email lorem@ipsum.com</div>
                </div>
            </div>

            <div class="block">
                <label>Agenda of the day</label>
                <div class="block2">
                    <div class="left">10:00 to 12:00</div>
                    <div class="right">
                        <div>Lorem 1 ipsum...</div>
                        <div>Lorem 2 ipsum...</div>
                    </div>
                </div>

                <div class="block2">
                    <div class="left">2:00pm to 4:00pm</div>
                    <div class="right">
                        <div>Lorem 1 ipsum...</div>
                        <div>Lorem 2 ipsum...</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="right">
            <!-- MAPS -->
        </div>
    </div>
</div>