<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users">My Profile</a></li>
                <li class="active"><a href="/event/venue">Venue Information</a></li>
                <li><a href="/event/conf-lib">Conference Library</a></li>
                <li><a href="/event/gallery">Gallery</a></li>
                <li><a href="/event/survey">Survey</a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title">Venue Information</div>
        <div id="venue">
            <table>
                <tr><td>Venue Name</td><td>Venue Name Detail</td></tr>
                <tr><td>Venue Addr</td><td>Venue Addr Detail</td></tr>
                <tr><td>Venue Hours</td><td>Hours Detail</td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Contact Information</td><td>Tel 155 555 555 555</td></tr>
                <tr><td></td><td>email lorem@ipsum.com</td></tr>
                
                <tr><td>&nbsp;</td></tr>
                <tr><td>Agenda of the day</td><td>Tel 155 555 555 555</td></tr>
                <tr><td></td><td>email lorem@ipsum.com</td></tr>
            </table>
        </div>
    </div>
    
</div>