<div class="event">
    
    <div id="menu">
        <div id="menu-wrapper">
            <ul>
                <li><a href="/users"><?php echo $this->translate('my_profile') ?></a></li>
                <li><a href="/event/agenda"><?php echo $this->translate('agenda') ?></a></li>
                <li><a href="/event/conf"><?php echo $this->translate('conference_speakers') ?></a></li>
                <li class="active"><a href="/event/venue"><?php echo $this->translate('venue') ?></a></li>
                <li><a href="/event/hospitality"><?php echo $this->translate('hospitality') ?></a></li>
                <li><a href="/event/survey"><?php echo $this->translate('survey') ?></a></li>
                <li><a href="/event/photowall"><?php echo $this->translate('photowall') ?></a></li>
                <li><a href="/event/contact"><?php echo $this->translate('contact_rsvp') ?></a></li>
                <li class="logout"><a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><?php echo $this->translate('logout') ?></a></li>
            </ul>
        </div>
    </div>
    
    <div id="main-content">
        <div id="main-content-title"><?php echo $this->translate('venue') ?></div>
        
        <?php if (Zend_Registry::get('Zend_Translate')->getLocale() == 'en') { ?>
                
																																						

               
        
                <div class="block">
                     <div class="block-title">CONFERENCE & GALA DINNER VENUE</div>
                     <div class="sub-block">
                         <label class="sub-block-title">SHANGHAI EXPO CENTRE</label>
                         <ul>
                             <li>SHANGHAI EXPO CENTRE CO., LTD.</li>
                             <li>website：<a href="http://www.secc.com.cn">http://www.secc.com.cn</a></li>
                             <li>1500 Expo Avenue Pudong District, Shanghai, China</li>
                         </ul>
                     </div>
                     <div class="sub-block">
                         <img src="/medias/images/sh_expo_center_1.jpg" width="500" height="400"/>
                         <img src="/medias/images/sh_expo_center_2.jpg" width="500" height="400"/>
                         <img src="/medias/images/sh_expo_center_3.jpg" width="1000" />
                     </div>
                     
                     <div class="sub-block full">
                         <label class="sub-block-title" style="font-size: 18px; width:100%;">VENUE MAPS</label>
                         <iframe width="700" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?ie=UTF8&amp;q=%E4%B8%8A%E6%B5%B7%E4%B8%96%E5%8D%9A%E4%B8%AD%E5%BF%83&amp;fb=1&amp;hq=%E4%B8%96%E5%8D%9A%E4%B8%AD%E5%BF%83&amp;hnear=0x35b27040b1f53c33:0x295129423c364a1,%E4%B8%8A%E6%B5%B7&amp;cid=0,0,6161769494885773964&amp;t=m&amp;brcurrent=3,0x35b27aa1b75f5a7d:0x33a77a770ab63b1b,0,0x35b27a9c437d5d51:0xeced90439ee1369a%3B5,0,0&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
                     </div>
                
                    <div class="sub-block full"><label class="sub-block-title" style="font-size: 18px;">TRANSFERS</label></div>
                    <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_1">From Hongqiao airport</label></a><div class="iframe" id="iframe_1"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+Pudong+International+Airport,+Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.178735,121.642685&amp;sspn=0.280219,0.617294&amp;geocode=FeyE2wEdi39CByn1jyGq24-tNTHku9n2TQ4s6Q%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;mra=prev&amp;t=m&amp;z=12&amp;iwloc=ddw1&amp;output=embed"></iframe></div></div>
                    <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_2">From Pudong airport</label></a><div class="iframe" id="iframe_2"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=SHANGHAI+hongqiao+airport&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.171391,121.69487&amp;sspn=0.140121,0.308647&amp;geocode=FWgL3AEdRXI7ByH22byHt5bV0in_6aLljWayNTH22byHt5bV0g%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;mra=ls&amp;t=m&amp;z=12&amp;output=embed"></iframe></div></div>
                    <div class="sub-block half-width"><a href="#"><label  class="transfer" id="transfer_3">From Shanghai railway station</label></a><div class="iframe" id="iframe_3"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?f=d&amp;source=s_d&amp;saddr=%E5%A4%A7%E7%BB%9F%E8%B7%AF&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;geocode=Fe3W3AEdDFI9Bw%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;sll=31.211774,121.473942&amp;sspn=0.102183,0.198269&amp;hl=en&amp;mra=prev&amp;ie=UTF8&amp;t=m&amp;z=12&amp;output=embed"></iframe></div></div>
                    <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_4">From Shanghai south railway station</label></a><div class="iframe" id="iframe_4"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+South+Railway+Station,+Shanghai,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.211921,121.475143&amp;sspn=0.140061,0.308647&amp;geocode=FeBh2wEd_OA8BymJo4e7u2SyNTGMmy4R-UwOfA%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;oq=Shanghai+SOUTH+Railway+Station,+Shanghai,+China&amp;mra=ls&amp;t=m&amp;vpsrc=0&amp;ll=31.174503,121.461754&amp;spn=0.040003,0.064661&amp;output=embed"></iframe></div></div>
                    <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_5">From Shanghai west railway station</label></a><div class="iframe" id="iframe_5"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+West+Railway+Station,+Shanghai,+Taopu+Road,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.174503,121.461754&amp;sspn=0.070058,0.154324&amp;geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;oq=Shanghai+WEST+Railway+Station,+Shanghai,+China&amp;mra=ls&amp;t=m&amp;z=13&amp;output=embed"></iframe></div></div>
                </div>
        
                     
        <?php } else { ?>
                
       																																							 <table>
									

        
                <div class="block">
                     <div class="block-title">会议和晚宴地点</div>
                     <div class="sub-block">
                         <label class="sub-block-title">上海世博中心</label>
                         <ul>
                             <li>上海世博中心有限公司</li>
                             <li>网址：<a href="http://www.secc.com.cn">http://www.secc.com.cn</a></li>
                             <li>上海市浦东新区世博大道1500号</li>
                         </ul>
                     </div>

                     <div class="sub-block">
                         <img src="/medias/images/sh_expo_center_1.jpg" width="500" height="400"/>
                         <img src="/medias/images/sh_expo_center_2.jpg" width="500" height="400"/>
                         <img src="/medias/images/sh_expo_center_3.jpg" width="1000" />
                     </div>

                     <div class="sub-block full">
                         <label class="sub-block-title" style="font-size: 18px; width:100%;">场地地图</label>
                         <iframe width="700" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://ditu.google.cn/maps?ie=UTF8&amp;q=%E4%B8%8A%E6%B5%B7%E4%B8%96%E5%8D%9A%E4%B8%AD%E5%BF%83&amp;fb=1&amp;hq=%E4%B8%96%E5%8D%9A%E4%B8%AD%E5%BF%83&amp;hnear=0x35b27040b1f53c33:0x295129423c364a1,%E4%B8%8A%E6%B5%B7&amp;cid=0,0,6161769494885773964&amp;t=m&amp;brcurrent=3,0x35b27aa1b75f5a7d:0x33a77a770ab63b1b,0,0x35b27a9c437d5d51:0xeced90439ee1369a%3B5,0,0&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
                     </div>
                     
                     <div class="sub-block full"><label class="sub-block-title" style="font-size: 18px; width:100%;">交通信息</label></div>
                     <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_1">从上海虹桥国际机场</label></a><div class="iframe" id="iframe_1"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+Pudong+International+Airport,+Shanghai+Pudong+International+Airport,+900%E5%8F%B7+Qihang+Rd,+Pudong,+Shanghai,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.178735,121.642685&amp;sspn=0.280219,0.617294&amp;geocode=FeyE2wEdi39CByn1jyGq24-tNTHku9n2TQ4s6Q%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;mra=prev&amp;t=m&amp;z=12&amp;iwloc=ddw1&amp;output=embed"></iframe></div></div>
                     <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_2">从上海浦东国际机场</label></a><div class="iframe" id="iframe_2"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=SHANGHAI+hongqiao+airport&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.171391,121.69487&amp;sspn=0.140121,0.308647&amp;geocode=FWgL3AEdRXI7ByH22byHt5bV0in_6aLljWayNTH22byHt5bV0g%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;mra=ls&amp;t=m&amp;z=12&amp;output=embed"></iframe></div></div>
                     <div class="sub-block half-width"><a href="#"><label  class="transfer" id="transfer_3">从上海火车站</label></a><div class="iframe" id="iframe_3"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?f=d&amp;source=s_d&amp;saddr=%E5%A4%A7%E7%BB%9F%E8%B7%AF&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;geocode=Fe3W3AEdDFI9Bw%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;sll=31.211774,121.473942&amp;sspn=0.102183,0.198269&amp;hl=en&amp;mra=prev&amp;ie=UTF8&amp;t=m&amp;z=12&amp;output=embed"></iframe></div></div>
                     <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_4">从上海南站</label></a><div class="iframe" id="iframe_4"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+South+Railway+Station,+Shanghai,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.211921,121.475143&amp;sspn=0.140061,0.308647&amp;geocode=FeBh2wEd_OA8BymJo4e7u2SyNTGMmy4R-UwOfA%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;oq=Shanghai+SOUTH+Railway+Station,+Shanghai,+China&amp;mra=ls&amp;t=m&amp;vpsrc=0&amp;ll=31.174503,121.461754&amp;spn=0.040003,0.064661&amp;output=embed"></iframe></iframe></div></div>
                     <div class="sub-block half-width"><a href="#"><label class="transfer" id="transfer_5">从上海西站</label></a><div class="iframe" id="iframe_5"><iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.de/maps?saddr=Shanghai+West+Railway+Station,+Shanghai,+Taopu+Road,+China&amp;daddr=Expo+Center,+1500%E5%8F%B7+Shibo+Avenue,+Pudong,+Shanghai,+China&amp;hl=en&amp;ie=UTF8&amp;sll=31.174503,121.461754&amp;sspn=0.070058,0.154324&amp;geocode=FTMK3QEdxXI8Bylj-xSFqG-yNTH52qzqQXVCJQ%3BFUPd2wEd88Y9BynNRAgt9XqyNTGMMoGKtQCDVQ&amp;oq=Shanghai+WEST+Railway+Station,+Shanghai,+China&amp;mra=ls&amp;t=m&amp;z=13&amp;output=embed"></iframe></div></div>
                </div>
                     
        <?php } ?>
        <div class="clear"></div>
    </div>
</div>

<script type="text/javascript">
$(function() {
    $('label.transfer').click(function(){
        var id = ($(this).attr('id').split('_'))['1'];
   
        if ($('#iframe_'+id).is(":visible") )
            $('#iframe_' + id).slideUp();
        else 
            $('#iframe_' + id).slideDown();
        return false;
    });
});
</script>