<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Naviland Cargo</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/layout.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/default.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery.timepicker.css"/>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery-ui.css" />
    <script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
    <script src="<?php echo $this->baseUrl() ?>/medias/js/libs/jquery-1.7.2.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/medias/admin/components/ui/jquery-ui-1.9.2.custom.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/medias/js/jquery.timepicker.min.js"></script>
</head>
<body>
    <!--[if lt IE 7]><p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p><![endif]-->
    <div id="wrap">
        
        <!-- start header -->
        <div id="header">
            <div id="header-wrapper">
                <div id="header-title">
                    <a href="/">
                        <div id="title-one">2013 JAGUAR LAND ROVER CHINA</div>
                        <div id="title-two">DEALER CONFERENCE</div>
                        <div id="title-calque"></div>
                        <div id="title-three">2013 年捷豹路虎中国经销商大会</div>
                    </a>
                </div>
                <div id="logo"><img src="/medias/images/logo.png"></div>
            </div>
        </div>
        <!-- end header -->
        
        
        <!-- start main -->
        <div id="main">
            <div id="main-wrapper">
            <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <!-- end main -->
        
    </div>
    
</body>
</html>
