<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Naviland Cargo</title>
    <link rel="icon" href="<?php echo $this->baseUrl(); ?>/medias/images/favicon.png">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/layout.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/default.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/menu.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/medias/css/jquery-ui.css" />
    <script type="text/javascript">var baseUrl = '<?php echo $this->baseUrl(); ?>';</script>
    <script src="<?php echo $this->baseUrl() ?>/medias/js/libs/jquery-1.7.2.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/medias/admin/components/ui/jquery-ui-1.9.2.custom.min.js"></script>
</head>
<body>
    <!--[if lt IE 7]><p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p><![endif]-->
    <div id="wrap">
        
        <!-- start header -->
        <div id="header">
            <div style="text-align: center;">HEADER</div>
            
            <?php if (isset($this->isLogged)) { ?>
            <div id="account_info">
                <div> <!--<b>Hi,</b> <b class="red"><?php echo $this->email; ?></b>  -->
                    <a href="<?php echo $this->url(array('controller' => 'users','action' => 'logout'), 'default', true); ?>"><b >Logout</b> </a>
                </div>
            </div>
            <?php } ?>
            
            <div id="logo"></div>
        </div>
        <!-- end header -->
        
        <!-- start main -->
        <div id="main">
            <?php echo $this->layout()->content; ?>
        </div>
        <!-- end main -->
        
    </div>
</body>
</html>
